CREATE TABLE "СТАТУСЫ_ИГР" ("КОД_СТАТУСА_ИГРЫ" VARCHAR2(40 CHAR) PRIMARY KEY,"НАИМЕНОВАНИЕ" VARCHAR2(50 CHAR) NOT NULL UNIQUE);
CREATE TABLE "СТАТУСЫ_УЧАСТНИКОВ" ("КОД_СТАТУСА_УЧАСТНИКА" VARCHAR2(40 CHAR) PRIMARY KEY,"НАИМЕНОВАНИЕ" VARCHAR2(50 CHAR) NOT NULL UNIQUE);
CREATE TABLE "СТАТУСЫ_АУКЦИОНОВ" ("КОД_СТАТУСА_АУКЦИОНА" VARCHAR2(40 CHAR) PRIMARY KEY,"НАИМЕНОВАНИЕ" VARCHAR2(50 CHAR) NOT NULL UNIQUE);
CREATE TABLE "ТИПЫ_ДЕЙСТВИЙ" ("КОД_ДЕЙСТВИЯ" VARCHAR2(60 CHAR) PRIMARY KEY,"НАИМЕНОВАНИЕ" VARCHAR2(100 CHAR) NOT NULL UNIQUE);
CREATE TABLE "СОСТОЯНИЯ_ХОДА" ("КОД_СОСТОЯНИЯ_ХОДА" VARCHAR2(40 CHAR) PRIMARY KEY,"НАИМЕНОВАНИЕ" VARCHAR2(100 CHAR) NOT NULL UNIQUE,"ОПИСАНИЕ" VARCHAR2(255 CHAR));

CREATE TABLE "ПОЛЬЗОВАТЕЛИ" (
 "ID_ПОЛЬЗОВАТЕЛЯ" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "ЛОГИН" VARCHAR2(50 CHAR) NOT NULL UNIQUE,
 "ПАРОЛЬ_ХЭШ" VARCHAR2(255 CHAR) NOT NULL,
 "ДАТА_РЕГИСТРАЦИИ" DATE DEFAULT SYSDATE NOT NULL,
 CONSTRAINT "CHK_ПОЛЬЗОВАТЕЛИ_ЛОГИН" CHECK (TRIM("ЛОГИН") IS NOT NULL));

CREATE TABLE "КЛЕТКИ" (
 "ID_КЛЕТКИ" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "НАЗВАНИЕ" VARCHAR2(50 CHAR) NOT NULL,"ТИП" VARCHAR2(30 CHAR) NOT NULL,"ПОЗИЦИЯ" NUMBER(2) NOT NULL UNIQUE,
 "ЦВЕТОВАЯ_ГРУППА" VARCHAR2(20 CHAR),"ЦЕНА_ПОКУПКИ" NUMBER,"БАЗОВАЯ_РЕНТА" NUMBER,"РЕНТА_1_ДОМ" NUMBER,
 "РЕНТА_2_ДОМА" NUMBER,"РЕНТА_ОТЕЛЬ" NUMBER,"ЦЕНА_ДОМА" NUMBER,"БОНУС_СТАРТА" NUMBER,
 CONSTRAINT "CHK_КЛЕТКИ_ТИП" CHECK ("ТИП" IN ('Старт','Улица','Коммунальная','Шанс')),
 CONSTRAINT "CHK_КЛЕТКИ_ПОЗ" CHECK ("ПОЗИЦИЯ" BETWEEN 1 AND 12),
 CONSTRAINT "CHK_КЛЕТКИ_ЦЕНА" CHECK ("ЦЕНА_ПОКУПКИ" IS NULL OR "ЦЕНА_ПОКУПКИ">=0),
 CONSTRAINT "CHK_КЛЕТКИ_Р0" CHECK ("БАЗОВАЯ_РЕНТА" IS NULL OR "БАЗОВАЯ_РЕНТА">=0),
 CONSTRAINT "CHK_КЛЕТКИ_Р1" CHECK ("РЕНТА_1_ДОМ" IS NULL OR "РЕНТА_1_ДОМ">=0),
 CONSTRAINT "CHK_КЛЕТКИ_Р2" CHECK ("РЕНТА_2_ДОМА" IS NULL OR "РЕНТА_2_ДОМА">=0),
 CONSTRAINT "CHK_КЛЕТКИ_РО" CHECK ("РЕНТА_ОТЕЛЬ" IS NULL OR "РЕНТА_ОТЕЛЬ">=0),
 CONSTRAINT "CHK_КЛЕТКИ_ДОМ" CHECK ("ЦЕНА_ДОМА" IS NULL OR "ЦЕНА_ДОМА">=0),
 CONSTRAINT "CHK_КЛЕТКИ_БОНУС" CHECK ("БОНУС_СТАРТА" IS NULL OR "БОНУС_СТАРТА">=0));

CREATE TABLE "ИГРЫ" (
 "ID_ИГРЫ" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "ID_ХОСТА" NUMBER NOT NULL,"ID_ТЕКУЩЕГО_УЧАСТНИКА" NUMBER,"ID_ПОБЕДИТЕЛЯ" NUMBER,
 "КОД_СТАТУСА_ИГРЫ" VARCHAR2(40 CHAR) NOT NULL,"НАЗВАНИЕ" VARCHAR2(100 CHAR) NOT NULL,"ПАРОЛЬ_ХЭШ" VARCHAR2(255 CHAR),
 "ДАТА_СОЗДАНИЯ" DATE DEFAULT SYSDATE NOT NULL,"ДАТА_СТАРТА" DATE,"ДАТА_ЗАВЕРШЕНИЯ" DATE,
 "МАКС_ИГРОКОВ" NUMBER(1) NOT NULL,"ВРЕМЯ_НАЧАЛА_ХОДА" DATE,"КОД_СОСТОЯНИЯ_ХОДА" VARCHAR2(40 CHAR),
 "ПОСЛЕДНЯЯ_КАРТА_ШАНСА" VARCHAR2(255 CHAR),
 CONSTRAINT "FK_ИГРЫ_ХОСТ" FOREIGN KEY ("ID_ХОСТА") REFERENCES "ПОЛЬЗОВАТЕЛИ"("ID_ПОЛЬЗОВАТЕЛЯ"),
 CONSTRAINT "FK_ИГРЫ_СТАТУС" FOREIGN KEY ("КОД_СТАТУСА_ИГРЫ") REFERENCES "СТАТУСЫ_ИГР"("КОД_СТАТУСА_ИГРЫ"),
 CONSTRAINT "FK_ИГРЫ_СОСТ" FOREIGN KEY ("КОД_СОСТОЯНИЯ_ХОДА") REFERENCES "СОСТОЯНИЯ_ХОДА"("КОД_СОСТОЯНИЯ_ХОДА"),
 CONSTRAINT "CHK_ИГРЫ_МАКС" CHECK ("МАКС_ИГРОКОВ" BETWEEN 2 AND 4),
 CONSTRAINT "CHK_ИГРЫ_СТАРТ" CHECK ("ДАТА_СТАРТА" IS NULL OR "ДАТА_СТАРТА">="ДАТА_СОЗДАНИЯ"),
 CONSTRAINT "CHK_ИГРЫ_ФИНИШ" CHECK ("ДАТА_ЗАВЕРШЕНИЯ" IS NULL OR "ДАТА_ЗАВЕРШЕНИЯ">="ДАТА_СОЗДАНИЯ"));

CREATE TABLE "УЧАСТНИКИ" (
 "ID_УЧАСТНИКА" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "ID_ИГРЫ" NUMBER NOT NULL,"ID_ПОЛЬЗОВАТЕЛЯ" NUMBER NOT NULL,"ID_ПОЗИЦИИ" NUMBER NOT NULL,
 "БАЛАНС" NUMBER DEFAULT 1500 NOT NULL,"ОЧЕРЕДЬ_ХОДА" NUMBER(1),"КОД_СТАТУСА_УЧАСТНИКА" VARCHAR2(40 CHAR) NOT NULL,
 "ГОТОВ" NUMBER(1) DEFAULT 0 NOT NULL,"КОЛ_ТАЙМАУТОВ" NUMBER(1) DEFAULT 0 NOT NULL,
 CONSTRAINT "FK_УЧ_ИГРА" FOREIGN KEY ("ID_ИГРЫ") REFERENCES "ИГРЫ"("ID_ИГРЫ"),
 CONSTRAINT "FK_УЧ_ПОЛЬЗ" FOREIGN KEY ("ID_ПОЛЬЗОВАТЕЛЯ") REFERENCES "ПОЛЬЗОВАТЕЛИ"("ID_ПОЛЬЗОВАТЕЛЯ"),
 CONSTRAINT "FK_УЧ_ПОЗ" FOREIGN KEY ("ID_ПОЗИЦИИ") REFERENCES "КЛЕТКИ"("ID_КЛЕТКИ"),
 CONSTRAINT "FK_УЧ_СТАТ" FOREIGN KEY ("КОД_СТАТУСА_УЧАСТНИКА") REFERENCES "СТАТУСЫ_УЧАСТНИКОВ"("КОД_СТАТУСА_УЧАСТНИКА"),
 CONSTRAINT "UQ_УЧ_ИГРА_ПОЛЬЗ" UNIQUE ("ID_ИГРЫ","ID_ПОЛЬЗОВАТЕЛЯ"),
 CONSTRAINT "CHK_УЧ_ГОТОВ" CHECK ("ГОТОВ" IN (0,1)),
 CONSTRAINT "CHK_УЧ_ТАЙМ" CHECK ("КОЛ_ТАЙМАУТОВ" BETWEEN 0 AND 2),
 CONSTRAINT "CHK_УЧ_ОЧ" CHECK ("ОЧЕРЕДЬ_ХОДА" IS NULL OR "ОЧЕРЕДЬ_ХОДА" BETWEEN 1 AND 4));
ALTER TABLE "ИГРЫ" ADD CONSTRAINT "FK_ИГРЫ_ТЕК" FOREIGN KEY ("ID_ТЕКУЩЕГО_УЧАСТНИКА") REFERENCES "УЧАСТНИКИ"("ID_УЧАСТНИКА");
ALTER TABLE "ИГРЫ" ADD CONSTRAINT "FK_ИГРЫ_ПОБ" FOREIGN KEY ("ID_ПОБЕДИТЕЛЯ") REFERENCES "УЧАСТНИКИ"("ID_УЧАСТНИКА");

CREATE TABLE "КАРТЫ_ШАНСА" (
 "ID_КАРТЫ" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"ID_ЦЕЛЕВОЙ_КЛЕТКИ" NUMBER,
 "ТИП_ЭФФЕКТА" VARCHAR2(20 CHAR) NOT NULL,"СУММА_ИЗМЕНЕНИЯ" NUMBER,"ТЕКСТ_СОБЫТИЯ" VARCHAR2(255 CHAR) NOT NULL,
 CONSTRAINT "FK_КАРТЫ_ЦЕЛЬ" FOREIGN KEY ("ID_ЦЕЛЕВОЙ_КЛЕТКИ") REFERENCES "КЛЕТКИ"("ID_КЛЕТКИ"),
 CONSTRAINT "CHK_КАРТЫ" CHECK (("ТИП_ЭФФЕКТА" IN ('Премия','Штраф') AND "СУММА_ИЗМЕНЕНИЯ">0 AND "ID_ЦЕЛЕВОЙ_КЛЕТКИ" IS NULL) OR ("ТИП_ЭФФЕКТА"='Перемещение' AND "ID_ЦЕЛЕВОЙ_КЛЕТКИ" IS NOT NULL AND "СУММА_ИЗМЕНЕНИЯ" IS NULL)));

CREATE TABLE "ВЛАДЕНИЯ" (
 "ID_ВЛАДЕНИЯ" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"ID_ИГРЫ" NUMBER NOT NULL,"ID_КЛЕТКИ" NUMBER NOT NULL,
 "ID_ВЛАДЕЛЬЦА" NUMBER,"КОЛВО_ДОМОВ" NUMBER(1) DEFAULT 0 NOT NULL,"ЗАЛОЖЕНА" NUMBER(1) DEFAULT 0 NOT NULL,
 CONSTRAINT "FK_ВЛАД_ИГРА" FOREIGN KEY ("ID_ИГРЫ") REFERENCES "ИГРЫ"("ID_ИГРЫ"),
 CONSTRAINT "FK_ВЛАД_КЛЕТКА" FOREIGN KEY ("ID_КЛЕТКИ") REFERENCES "КЛЕТКИ"("ID_КЛЕТКИ"),
 CONSTRAINT "FK_ВЛАД_ВЛАД" FOREIGN KEY ("ID_ВЛАДЕЛЬЦА") REFERENCES "УЧАСТНИКИ"("ID_УЧАСТНИКА"),
 CONSTRAINT "UQ_ВЛАД_ИГРА_КЛ" UNIQUE ("ID_ИГРЫ","ID_КЛЕТКИ"),
 CONSTRAINT "CHK_ВЛАД_ДОМА" CHECK ("КОЛВО_ДОМОВ" BETWEEN 0 AND 3),
 CONSTRAINT "CHK_ВЛАД_ЗАЛОГ" CHECK ("ЗАЛОЖЕНА" IN (0,1)),
 CONSTRAINT "CHK_ВЛАД_ЗАЛОГ_ДОМ" CHECK ("ЗАЛОЖЕНА"=0 OR "КОЛВО_ДОМОВ"=0));

CREATE TABLE "АУКЦИОНЫ" (
 "ID_АУКЦИОНА" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"ID_ИГРЫ" NUMBER NOT NULL,"ID_КЛЕТКИ" NUMBER NOT NULL,
 "ID_ПОБЕДИТЕЛЯ" NUMBER,"КОД_СТАТУСА_АУКЦИОНА" VARCHAR2(40 CHAR) NOT NULL,"СТАРТ_ЦЕНА" NUMBER NOT NULL,"ФИНАЛ_ЦЕНА" NUMBER,
 "ДАТА_НАЧАЛА" DATE DEFAULT SYSDATE NOT NULL,"ДАТА_ОКОНЧАНИЯ" DATE,
 CONSTRAINT "FK_АУК_ИГРА" FOREIGN KEY ("ID_ИГРЫ") REFERENCES "ИГРЫ"("ID_ИГРЫ"),
 CONSTRAINT "FK_АУК_КЛ" FOREIGN KEY ("ID_КЛЕТКИ") REFERENCES "КЛЕТКИ"("ID_КЛЕТКИ"),
 CONSTRAINT "FK_АУК_ПОБ" FOREIGN KEY ("ID_ПОБЕДИТЕЛЯ") REFERENCES "УЧАСТНИКИ"("ID_УЧАСТНИКА"),
 CONSTRAINT "FK_АУК_СТАТ" FOREIGN KEY ("КОД_СТАТУСА_АУКЦИОНА") REFERENCES "СТАТУСЫ_АУКЦИОНОВ"("КОД_СТАТУСА_АУКЦИОНА"),
 CONSTRAINT "CHK_АУК_СТАРТ" CHECK ("СТАРТ_ЦЕНА">=0),CONSTRAINT "CHK_АУК_ФИНАЛ" CHECK ("ФИНАЛ_ЦЕНА" IS NULL OR "ФИНАЛ_ЦЕНА">=0),
 CONSTRAINT "CHK_АУК_ДАТА" CHECK ("ДАТА_ОКОНЧАНИЯ" IS NULL OR "ДАТА_ОКОНЧАНИЯ">="ДАТА_НАЧАЛА"));

CREATE TABLE "СТАВКИ" (
 "ID_СТАВКИ" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"ID_АУКЦИОНА" NUMBER NOT NULL,"ID_УЧАСТНИКА" NUMBER NOT NULL,
 "СУММА" NUMBER NOT NULL,"ДАТА_ВРЕМЯ" DATE DEFAULT SYSDATE NOT NULL,
 CONSTRAINT "FK_СТАВКИ_АУК" FOREIGN KEY ("ID_АУКЦИОНА") REFERENCES "АУКЦИОНЫ"("ID_АУКЦИОНА"),
 CONSTRAINT "FK_СТАВКИ_УЧ" FOREIGN KEY ("ID_УЧАСТНИКА") REFERENCES "УЧАСТНИКИ"("ID_УЧАСТНИКА"),
 CONSTRAINT "UQ_СТАВКИ" UNIQUE ("ID_АУКЦИОНА","ID_УЧАСТНИКА"),CONSTRAINT "CHK_СТАВКИ" CHECK ("СУММА">=0));

CREATE TABLE "ЖУРНАЛ_ДЕЙСТВИЙ" (
 "ID_ДЕЙСТВИЯ" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"ID_ИГРЫ" NUMBER NOT NULL,"ID_УЧАСТНИКА" NUMBER,"ID_КЛЕТКИ" NUMBER,
 "КОД_ДЕЙСТВИЯ" VARCHAR2(60 CHAR) NOT NULL,"СУММА" NUMBER,"ДАТА_ВРЕМЯ" DATE DEFAULT SYSDATE NOT NULL,
 CONSTRAINT "FK_ЖУРНАЛ_ИГРА" FOREIGN KEY ("ID_ИГРЫ") REFERENCES "ИГРЫ"("ID_ИГРЫ"),
 CONSTRAINT "FK_ЖУРНАЛ_УЧ" FOREIGN KEY ("ID_УЧАСТНИКА") REFERENCES "УЧАСТНИКИ"("ID_УЧАСТНИКА"),
 CONSTRAINT "FK_ЖУРНАЛ_КЛ" FOREIGN KEY ("ID_КЛЕТКИ") REFERENCES "КЛЕТКИ"("ID_КЛЕТКИ"),
 CONSTRAINT "FK_ЖУРНАЛ_ТИП" FOREIGN KEY ("КОД_ДЕЙСТВИЯ") REFERENCES "ТИПЫ_ДЕЙСТВИЙ"("КОД_ДЕЙСТВИЯ"));

CREATE TABLE "ЧАТ" (
 "ID_СООБЩЕНИЯ" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"ID_УЧАСТНИКА" NUMBER NOT NULL,
 "ТЕКСТ" VARCHAR2(4000 CHAR) NOT NULL,"ДАТА_ВРЕМЯ" DATE DEFAULT SYSDATE NOT NULL,
 CONSTRAINT "FK_ЧАТ_УЧ" FOREIGN KEY ("ID_УЧАСТНИКА") REFERENCES "УЧАСТНИКИ"("ID_УЧАСТНИКА"),
 CONSTRAINT "CHK_ЧАТ_ТЕКСТ" CHECK (TRIM("ТЕКСТ") IS NOT NULL));

CREATE INDEX "IX_УЧ_ИГРА" ON "УЧАСТНИКИ"("ID_ИГРЫ");
CREATE UNIQUE INDEX "UQ_УЧ_ИГРА_ОЧ" ON "УЧАСТНИКИ"(
 CASE WHEN "ОЧЕРЕДЬ_ХОДА" IS NOT NULL THEN "ID_ИГРЫ" END,
 "ОЧЕРЕДЬ_ХОДА"
);
CREATE INDEX "IX_ВЛАД_ИГРА" ON "ВЛАДЕНИЯ"("ID_ИГРЫ");
CREATE INDEX "IX_АУК_ИГРА" ON "АУКЦИОНЫ"("ID_ИГРЫ");
CREATE INDEX "IX_ЖУРНАЛ_ИГРА" ON "ЖУРНАЛ_ДЕЙСТВИЙ"("ID_ИГРЫ","ДАТА_ВРЕМЯ");
