CREATE OR REPLACE PACKAGE BODY monopoly AS
 FUNCTION participant_game(pid NUMBER) RETURN NUMBER IS g NUMBER; BEGIN SELECT "ID_ИГРЫ" INTO g FROM "УЧАСТНИКИ" WHERE "ID_УЧАСТНИКА"=pid; RETURN g; EXCEPTION WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20001,'Участник не найден'); END;
 PROCEDURE add_action(p_game_id NUMBER,p_participant_id NUMBER DEFAULT NULL,p_cell_id NUMBER DEFAULT NULL,p_action_code VARCHAR2,p_amount NUMBER DEFAULT NULL) IS n NUMBER; BEGIN
  IF p_participant_id IS NOT NULL THEN SELECT COUNT(*) INTO n FROM "УЧАСТНИКИ" WHERE "ID_УЧАСТНИКА"=p_participant_id AND "ID_ИГРЫ"=p_game_id; IF n=0 THEN RAISE_APPLICATION_ERROR(-20002,'Участник не относится к игре'); END IF; END IF;
  IF p_cell_id IS NOT NULL THEN SELECT COUNT(*) INTO n FROM "КЛЕТКИ" WHERE "ID_КЛЕТКИ"=p_cell_id; IF n=0 THEN RAISE_APPLICATION_ERROR(-20003,'Клетка не найдена'); END IF; END IF;
  INSERT INTO "ЖУРНАЛ_ДЕЙСТВИЙ"("ID_ИГРЫ","ID_УЧАСТНИКА","ID_КЛЕТКИ","КОД_ДЕЙСТВИЯ","СУММА","ДАТА_ВРЕМЯ") VALUES(p_game_id,p_participant_id,p_cell_id,p_action_code,p_amount,SYSDATE);
 END;
 PROCEDURE return_properties_to_bank(p_participant_id NUMBER) IS BEGIN UPDATE "ВЛАДЕНИЯ" SET "ID_ВЛАДЕЛЬЦА"=NULL,"КОЛВО_ДОМОВ"=0,"ЗАЛОЖЕНА"=0 WHERE "ID_ВЛАДЕЛЬЦА"=p_participant_id; END;

 PROCEDURE register_user(p_login VARCHAR2,p_password VARCHAR2) IS
  password_hash "ПОЛЬЗОВАТЕЛИ"."ПАРОЛЬ_ХЭШ"%TYPE;
 BEGIN
  IF TRIM(p_login) IS NULL OR p_password IS NULL OR LENGTH(p_password)=0 THEN RAISE_APPLICATION_ERROR(-20010,'Логин и пароль обязательны'); END IF;
  SELECT RAWTOHEX(STANDARD_HASH(p_password, 'SHA256')) INTO password_hash FROM dual;
  INSERT INTO "ПОЛЬЗОВАТЕЛИ"("ЛОГИН","ПАРОЛЬ_ХЭШ","ДАТА_РЕГИСТРАЦИИ") VALUES(TRIM(p_login),password_hash,SYSDATE);
 EXCEPTION WHEN DUP_VAL_ON_INDEX THEN RAISE_APPLICATION_ERROR(-20011,'Логин уже занят'); END;
 FUNCTION authenticate_user(p_login VARCHAR2,p_password VARCHAR2) RETURN NUMBER IS
  id NUMBER;
  password_hash "ПОЛЬЗОВАТЕЛИ"."ПАРОЛЬ_ХЭШ"%TYPE;
 BEGIN
  SELECT RAWTOHEX(STANDARD_HASH(p_password, 'SHA256')) INTO password_hash FROM dual;
  SELECT "ID_ПОЛЬЗОВАТЕЛЯ" INTO id FROM "ПОЛЬЗОВАТЕЛИ" WHERE "ЛОГИН"=TRIM(p_login) AND "ПАРОЛЬ_ХЭШ"=password_hash;
  RETURN id;
 EXCEPTION WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20012,'Неверный логин или пароль'); END;

 PROCEDURE create_game(p_user_id NUMBER,p_game_name VARCHAR2,p_max_players NUMBER DEFAULT 4,p_room_password VARCHAR2 DEFAULT NULL,p_game_id OUT NUMBER) IS n NUMBER; start_id NUMBER; room_password_hash "ИГРЫ"."ПАРОЛЬ_ХЭШ"%TYPE; BEGIN
  IF p_max_players NOT BETWEEN 2 AND 4 THEN RAISE_APPLICATION_ERROR(-20020,'Количество игроков: 2–4'); END IF; IF TRIM(p_game_name) IS NULL THEN RAISE_APPLICATION_ERROR(-20021,'Название обязательно'); END IF;
  SELECT COUNT(*) INTO n FROM "ПОЛЬЗОВАТЕЛИ" WHERE "ID_ПОЛЬЗОВАТЕЛЯ"=p_user_id; IF n=0 THEN RAISE_APPLICATION_ERROR(-20022,'Пользователь не найден'); END IF;
  SELECT COUNT(*) INTO n FROM "УЧАСТНИКИ" u JOIN "ИГРЫ" g ON g."ID_ИГРЫ"=u."ID_ИГРЫ" WHERE u."ID_ПОЛЬЗОВАТЕЛЯ"=p_user_id AND g."КОД_СТАТУСА_ИГРЫ" IN('ОЖИДАНИЕ','ПРОВЕРКА_ГОТОВНОСТИ','АКТИВНА') AND u."КОД_СТАТУСА_УЧАСТНИКА" IN('В_ЛОББИ','АКТИВЕН'); IF n>0 THEN RAISE_APPLICATION_ERROR(-20023,'Пользователь уже в незавершённой игре'); END IF;
  SELECT "ID_КЛЕТКИ" INTO start_id FROM "КЛЕТКИ" WHERE "ПОЗИЦИЯ"=1;
  IF p_room_password IS NULL THEN
   room_password_hash:=NULL;
  ELSE
   SELECT RAWTOHEX(STANDARD_HASH(p_room_password, 'SHA256')) INTO room_password_hash FROM dual;
  END IF;
  INSERT INTO "ИГРЫ"("ID_ХОСТА","КОД_СТАТУСА_ИГРЫ","НАЗВАНИЕ","ПАРОЛЬ_ХЭШ","ДАТА_СОЗДАНИЯ","МАКС_ИГРОКОВ") VALUES(p_user_id,'ОЖИДАНИЕ',TRIM(p_game_name),room_password_hash,SYSDATE,p_max_players) RETURNING "ID_ИГРЫ" INTO p_game_id;
  INSERT INTO "УЧАСТНИКИ"("ID_ИГРЫ","ID_ПОЛЬЗОВАТЕЛЯ","ID_ПОЗИЦИИ","БАЛАНС","КОД_СТАТУСА_УЧАСТНИКА","ГОТОВ","КОЛ_ТАЙМАУТОВ") VALUES(p_game_id,p_user_id,start_id,c_start_balance,'В_ЛОББИ',0,0);
 END;
 FUNCTION list_waiting_games RETURN SYS_REFCURSOR IS rc SYS_REFCURSOR; BEGIN OPEN rc FOR SELECT g."ID_ИГРЫ",g."НАЗВАНИЕ",g."МАКС_ИГРОКОВ",COUNT(CASE WHEN u."КОД_СТАТУСА_УЧАСТНИКА"='В_ЛОББИ' THEN 1 END) "ЗАНЯТО",CASE WHEN g."ПАРОЛЬ_ХЭШ" IS NULL THEN 0 ELSE 1 END "ЕСТЬ_ПАРОЛЬ" FROM "ИГРЫ" g LEFT JOIN "УЧАСТНИКИ" u ON u."ID_ИГРЫ"=g."ID_ИГРЫ" WHERE g."КОД_СТАТУСА_ИГРЫ"='ОЖИДАНИЕ' GROUP BY g."ID_ИГРЫ",g."НАЗВАНИЕ",g."МАКС_ИГРОКОВ",g."ПАРОЛЬ_ХЭШ",g."ДАТА_СОЗДАНИЯ" HAVING COUNT(CASE WHEN u."КОД_СТАТУСА_УЧАСТНИКА"='В_ЛОББИ' THEN 1 END)<g."МАКС_ИГРОКОВ" ORDER BY g."ДАТА_СОЗДАНИЯ" DESC; RETURN rc; END;
 PROCEDURE join_game(p_user_id NUMBER,p_game_id NUMBER,p_room_password VARCHAR2 DEFAULT NULL) IS st VARCHAR2(40); h VARCHAR2(255); mx NUMBER; n NUMBER; sid NUMBER; ps VARCHAR2(40); pid NUMBER; entered_password_hash "ИГРЫ"."ПАРОЛЬ_ХЭШ"%TYPE; BEGIN
  IF p_room_password IS NULL THEN
   entered_password_hash:=NULL;
  ELSE
   SELECT RAWTOHEX(STANDARD_HASH(p_room_password, 'SHA256')) INTO entered_password_hash FROM dual;
  END IF;
  SELECT "КОД_СТАТУСА_ИГРЫ","ПАРОЛЬ_ХЭШ","МАКС_ИГРОКОВ" INTO st,h,mx FROM "ИГРЫ" WHERE "ID_ИГРЫ"=p_game_id FOR UPDATE; IF st<>'ОЖИДАНИЕ' THEN RAISE_APPLICATION_ERROR(-20030,'Комната недоступна'); END IF; IF h IS NOT NULL AND h<>entered_password_hash THEN RAISE_APPLICATION_ERROR(-20031,'Неверный пароль'); END IF;
  SELECT COUNT(*) INTO n FROM "УЧАСТНИКИ" WHERE "ID_ИГРЫ"=p_game_id AND "КОД_СТАТУСА_УЧАСТНИКА"='В_ЛОББИ'; IF n>=mx THEN RAISE_APPLICATION_ERROR(-20032,'Комната заполнена'); END IF;
  SELECT COUNT(*) INTO n FROM "УЧАСТНИКИ" u JOIN "ИГРЫ" g ON g."ID_ИГРЫ"=u."ID_ИГРЫ" WHERE u."ID_ПОЛЬЗОВАТЕЛЯ"=p_user_id AND g."ID_ИГРЫ"<>p_game_id AND g."КОД_СТАТУСА_ИГРЫ" IN('ОЖИДАНИЕ','ПРОВЕРКА_ГОТОВНОСТИ','АКТИВНА') AND u."КОД_СТАТУСА_УЧАСТНИКА" IN('В_ЛОББИ','АКТИВЕН'); IF n>0 THEN RAISE_APPLICATION_ERROR(-20033,'Пользователь уже в другой игре'); END IF;
  SELECT "ID_КЛЕТКИ" INTO sid FROM "КЛЕТКИ" WHERE "ПОЗИЦИЯ"=1;
  BEGIN SELECT "ID_УЧАСТНИКА","КОД_СТАТУСА_УЧАСТНИКА" INTO pid,ps FROM "УЧАСТНИКИ" WHERE "ID_ИГРЫ"=p_game_id AND "ID_ПОЛЬЗОВАТЕЛЯ"=p_user_id FOR UPDATE; IF ps='ИСКЛЮЧЕН' THEN RAISE_APPLICATION_ERROR(-20034,'Повторный вход запрещён'); END IF; IF ps<>'ПОКИНУЛ' THEN RAISE_APPLICATION_ERROR(-20035,'Вы уже в комнате'); END IF; UPDATE "УЧАСТНИКИ" SET "КОД_СТАТУСА_УЧАСТНИКА"='В_ЛОББИ',"ГОТОВ"=0,"ОЧЕРЕДЬ_ХОДА"=NULL,"КОЛ_ТАЙМАУТОВ"=0,"БАЛАНС"=c_start_balance,"ID_ПОЗИЦИИ"=sid WHERE "ID_УЧАСТНИКА"=pid;
  EXCEPTION WHEN NO_DATA_FOUND THEN INSERT INTO "УЧАСТНИКИ"("ID_ИГРЫ","ID_ПОЛЬЗОВАТЕЛЯ","ID_ПОЗИЦИИ","БАЛАНС","КОД_СТАТУСА_УЧАСТНИКА") VALUES(p_game_id,p_user_id,sid,c_start_balance,'В_ЛОББИ'); END;
 END;
 PROCEDURE abandon_waiting_game(p_user_id NUMBER,p_game_id NUMBER) IS h NUMBER; st VARCHAR2(40); BEGIN SELECT "ID_ХОСТА","КОД_СТАТУСА_ИГРЫ" INTO h,st FROM "ИГРЫ" WHERE "ID_ИГРЫ"=p_game_id FOR UPDATE; IF h<>p_user_id OR st NOT IN('ОЖИДАНИЕ','ПРОВЕРКА_ГОТОВНОСТИ') THEN RAISE_APPLICATION_ERROR(-20040,'Нельзя забросить игру'); END IF; UPDATE "ИГРЫ" SET "КОД_СТАТУСА_ИГРЫ"='ЗАБРОШЕНА',"ДАТА_ЗАВЕРШЕНИЯ"=SYSDATE,"ID_ТЕКУЩЕГО_УЧАСТНИКА"=NULL,"КОД_СОСТОЯНИЯ_ХОДА"=NULL WHERE "ID_ИГРЫ"=p_game_id; UPDATE "УЧАСТНИКИ" SET "КОД_СТАТУСА_УЧАСТНИКА"='ПОКИНУЛ',"ГОТОВ"=0 WHERE "ID_ИГРЫ"=p_game_id AND "КОД_СТАТУСА_УЧАСТНИКА"='В_ЛОББИ'; add_action(p_game_id,NULL,NULL,'ИГРА_ЗАБРОШЕНА',NULL); END;
 PROCEDURE leave_lobby(p_participant_id NUMBER) IS g NUMBER; usr NUMBER; h NUMBER; st VARCHAR2(40); BEGIN SELECT u."ID_ИГРЫ",u."ID_ПОЛЬЗОВАТЕЛЯ",x."ID_ХОСТА",x."КОД_СТАТУСА_ИГРЫ" INTO g,usr,h,st FROM "УЧАСТНИКИ" u JOIN "ИГРЫ" x ON x."ID_ИГРЫ"=u."ID_ИГРЫ" WHERE u."ID_УЧАСТНИКА"=p_participant_id FOR UPDATE; IF usr=h THEN abandon_waiting_game(usr,g); RETURN; END IF; IF st NOT IN('ОЖИДАНИЕ','ПРОВЕРКА_ГОТОВНОСТИ') THEN RAISE_APPLICATION_ERROR(-20041,'Игра уже началась'); END IF; UPDATE "УЧАСТНИКИ" SET "КОД_СТАТУСА_УЧАСТНИКА"='ПОКИНУЛ',"ГОТОВ"=0 WHERE "ID_УЧАСТНИКА"=p_participant_id; IF st='ПРОВЕРКА_ГОТОВНОСТИ' THEN UPDATE "ИГРЫ" SET "КОД_СТАТУСА_ИГРЫ"='ОЖИДАНИЕ' WHERE "ID_ИГРЫ"=g; UPDATE "УЧАСТНИКИ" SET "ГОТОВ"=0 WHERE "ID_ИГРЫ"=g AND "КОД_СТАТУСА_УЧАСТНИКА"='В_ЛОББИ'; END IF; END;
 PROCEDURE kick_participant(p_host_user_id NUMBER,p_participant_id NUMBER) IS g NUMBER; h NUMBER; tu NUMBER; st VARCHAR2(40); BEGIN SELECT u."ID_ИГРЫ",x."ID_ХОСТА",u."ID_ПОЛЬЗОВАТЕЛЯ",x."КОД_СТАТУСА_ИГРЫ" INTO g,h,tu,st FROM "УЧАСТНИКИ" u JOIN "ИГРЫ" x ON x."ID_ИГРЫ"=u."ID_ИГРЫ" WHERE u."ID_УЧАСТНИКА"=p_participant_id FOR UPDATE; IF h<>p_host_user_id THEN RAISE_APPLICATION_ERROR(-20042,'Только хост может исключать'); END IF; IF tu=h THEN RAISE_APPLICATION_ERROR(-20043,'Нельзя исключить хоста'); END IF; IF st NOT IN('ОЖИДАНИЕ','ПРОВЕРКА_ГОТОВНОСТИ') THEN RAISE_APPLICATION_ERROR(-20044,'Игра уже началась'); END IF; UPDATE "УЧАСТНИКИ" SET "КОД_СТАТУСА_УЧАСТНИКА"='ИСКЛЮЧЕН',"ГОТОВ"=0 WHERE "ID_УЧАСТНИКА"=p_participant_id; add_action(g,p_participant_id,NULL,'ИСКЛЮЧЕНИЕ_УЧАСТНИКА',NULL); IF st='ПРОВЕРКА_ГОТОВНОСТИ' THEN UPDATE "ИГРЫ" SET "КОД_СТАТУСА_ИГРЫ"='ОЖИДАНИЕ' WHERE "ID_ИГРЫ"=g; UPDATE "УЧАСТНИКИ" SET "ГОТОВ"=0 WHERE "ID_ИГРЫ"=g AND "КОД_СТАТУСА_УЧАСТНИКА"='В_ЛОББИ'; END IF; END;
 PROCEDURE request_start(p_game_id NUMBER,p_host_user_id NUMBER) IS h NUMBER; st VARCHAR2(40); n NUMBER; hp NUMBER; BEGIN SELECT "ID_ХОСТА","КОД_СТАТУСА_ИГРЫ" INTO h,st FROM "ИГРЫ" WHERE "ID_ИГРЫ"=p_game_id FOR UPDATE; IF h<>p_host_user_id OR st<>'ОЖИДАНИЕ' THEN RAISE_APPLICATION_ERROR(-20045,'Запуск недоступен'); END IF; SELECT COUNT(*) INTO n FROM "УЧАСТНИКИ" WHERE "ID_ИГРЫ"=p_game_id AND "КОД_СТАТУСА_УЧАСТНИКА"='В_ЛОББИ'; IF n<2 THEN RAISE_APPLICATION_ERROR(-20046,'Нужно минимум два игрока'); END IF; UPDATE "УЧАСТНИКИ" SET "ГОТОВ"=0 WHERE "ID_ИГРЫ"=p_game_id AND "КОД_СТАТУСА_УЧАСТНИКА"='В_ЛОББИ'; SELECT "ID_УЧАСТНИКА" INTO hp FROM "УЧАСТНИКИ" WHERE "ID_ИГРЫ"=p_game_id AND "ID_ПОЛЬЗОВАТЕЛЯ"=p_host_user_id; UPDATE "УЧАСТНИКИ" SET "ГОТОВ"=1 WHERE "ID_УЧАСТНИКА"=hp; UPDATE "ИГРЫ" SET "КОД_СТАТУСА_ИГРЫ"='ПРОВЕРКА_ГОТОВНОСТИ' WHERE "ID_ИГРЫ"=p_game_id; END;
 PROCEDURE set_ready(p_participant_id NUMBER,p_ready NUMBER) IS g NUMBER; st VARCHAR2(40); n NUMBER; ready NUMBER; BEGIN IF p_ready NOT IN(0,1) THEN RAISE_APPLICATION_ERROR(-20047,'Готовность: 0 или 1'); END IF; SELECT u."ID_ИГРЫ",x."КОД_СТАТУСА_ИГРЫ" INTO g,st FROM "УЧАСТНИКИ" u JOIN "ИГРЫ" x ON x."ID_ИГРЫ"=u."ID_ИГРЫ" WHERE u."ID_УЧАСТНИКА"=p_participant_id FOR UPDATE; IF st NOT IN('ОЖИДАНИЕ','ПРОВЕРКА_ГОТОВНОСТИ') THEN RAISE_APPLICATION_ERROR(-20048,'Готовность сейчас недоступна'); END IF; UPDATE "УЧАСТНИКИ" SET "ГОТОВ"=p_ready WHERE "ID_УЧАСТНИКА"=p_participant_id AND "КОД_СТАТУСА_УЧАСТНИКА"='В_ЛОББИ'; IF SQL%ROWCOUNT=0 THEN RAISE_APPLICATION_ERROR(-20049,'Участник не находится в комнате'); END IF; IF p_ready=1 THEN add_action(g,p_participant_id,NULL,'ПОДТВЕРЖДЕНИЕ_ГОТОВНОСТИ',NULL); END IF; SELECT COUNT(*),NVL(SUM("ГОТОВ"),0) INTO n,ready FROM "УЧАСТНИКИ" WHERE "ID_ИГРЫ"=g AND "КОД_СТАТУСА_УЧАСТНИКА"='В_ЛОББИ'; IF n>=2 AND ready=n THEN UPDATE "ИГРЫ" SET "КОД_СТАТУСА_ИГРЫ"='ПРОВЕРКА_ГОТОВНОСТИ',"ВРЕМЯ_НАЧАЛА_ХОДА"=SYSDATE WHERE "ID_ИГРЫ"=g; ELSE UPDATE "ИГРЫ" SET "КОД_СТАТУСА_ИГРЫ"='ОЖИДАНИЕ',"ВРЕМЯ_НАЧАЛА_ХОДА"=NULL WHERE "ID_ИГРЫ"=g; END IF; END;
 PROCEDURE start_game(p_game_id NUMBER,p_host_user_id NUMBER) IS h NUMBER; st VARCHAR2(40); n NUMBER; ready NUMBER; first_id NUMBER; ownn NUMBER; BEGIN SELECT "ID_ХОСТА","КОД_СТАТУСА_ИГРЫ" INTO h,st FROM "ИГРЫ" WHERE "ID_ИГРЫ"=p_game_id FOR UPDATE; IF h<>p_host_user_id OR st<>'ПРОВЕРКА_ГОТОВНОСТИ' THEN RAISE_APPLICATION_ERROR(-20050,'Игра не готова'); END IF; SELECT COUNT(*),SUM("ГОТОВ") INTO n,ready FROM "УЧАСТНИКИ" WHERE "ID_ИГРЫ"=p_game_id AND "КОД_СТАТУСА_УЧАСТНИКА"='В_ЛОББИ'; IF n NOT BETWEEN 2 AND 4 OR ready<>n THEN RAISE_APPLICATION_ERROR(-20051,'Не все готовы'); END IF; SELECT COUNT(*) INTO ownn FROM "ВЛАДЕНИЯ" WHERE "ID_ИГРЫ"=p_game_id; IF ownn>0 THEN RAISE_APPLICATION_ERROR(-20052,'Игра уже инициализирована'); END IF; UPDATE "УЧАСТНИКИ" SET "ОЧЕРЕДЬ_ХОДА"=NULL WHERE "ID_ИГРЫ"=p_game_id; MERGE INTO "УЧАСТНИКИ" u USING(SELECT "ID_УЧАСТНИКА",ROW_NUMBER() OVER(ORDER BY DBMS_RANDOM.VALUE,"ID_УЧАСТНИКА") rn FROM "УЧАСТНИКИ" WHERE "ID_ИГРЫ"=p_game_id AND "КОД_СТАТУСА_УЧАСТНИКА"='В_ЛОББИ') s ON(u."ID_УЧАСТНИКА"=s."ID_УЧАСТНИКА") WHEN MATCHED THEN UPDATE SET u."ОЧЕРЕДЬ_ХОДА"=s.rn,u."КОД_СТАТУСА_УЧАСТНИКА"='АКТИВЕН',u."БАЛАНС"=FLOOR(c_start_balance/n),u."КОЛ_ТАЙМАУТОВ"=0,u."ГОТОВ"=1; INSERT INTO "ВЛАДЕНИЯ"("ID_ИГРЫ","ID_КЛЕТКИ","ID_ВЛАДЕЛЬЦА","КОЛВО_ДОМОВ","ЗАЛОЖЕНА") SELECT p_game_id,"ID_КЛЕТКИ",NULL,0,0 FROM "КЛЕТКИ" WHERE "ТИП" IN('Улица','Коммунальная'); SELECT "ID_УЧАСТНИКА" INTO first_id FROM "УЧАСТНИКИ" WHERE "ID_ИГРЫ"=p_game_id AND "ОЧЕРЕДЬ_ХОДА"=1; UPDATE "ИГРЫ" SET "КОД_СТАТУСА_ИГРЫ"='АКТИВНА',"ДАТА_СТАРТА"=SYSDATE,"ID_ТЕКУЩЕГО_УЧАСТНИКА"=first_id,"ВРЕМЯ_НАЧАЛА_ХОДА"=SYSDATE,"КОД_СОСТОЯНИЯ_ХОДА"='ОЖИДАНИЕ_БРОСКА' WHERE "ID_ИГРЫ"=p_game_id; END;

 FUNCTION get_game_state(p_participant_id NUMBER) RETURN SYS_REFCURSOR IS rc SYS_REFCURSOR; BEGIN OPEN rc FOR SELECT g."ID_ИГРЫ",g."НАЗВАНИЕ",g."КОД_СТАТУСА_ИГРЫ",sg."НАИМЕНОВАНИЕ" "СТАТУС_ИГРЫ",g."КОД_СОСТОЯНИЯ_ХОДА",sh."НАИМЕНОВАНИЕ" "СОСТОЯНИЕ_ХОДА",g."ID_ТЕКУЩЕГО_УЧАСТНИКА",g."ID_ПОБЕДИТЕЛЯ",g."ВРЕМЯ_НАЧАЛА_ХОДА",g."ДАТА_СТАРТА",g."ДАТА_ЗАВЕРШЕНИЯ",g."ID_ХОСТА",g."МАКС_ИГРОКОВ",g."ПОСЛЕДНЯЯ_КАРТА_ШАНСА",CASE WHEN g."КОД_СТАТУСА_ИГРЫ"='ПРОВЕРКА_ГОТОВНОСТИ' THEN GREATEST(0,CEIL(c_ready_seconds-(SYSDATE-g."ВРЕМЯ_НАЧАЛА_ХОДА")*86400)) END "СЕКУНД_ДО_СТАРТА",CASE WHEN g."КОД_СТАТУСА_ИГРЫ"='АКТИВНА' AND g."ВРЕМЯ_НАЧАЛА_ХОДА" IS NOT NULL THEN GREATEST(0,CEIL(c_turn_minutes*60-(SYSDATE-g."ВРЕМЯ_НАЧАЛА_ХОДА")*86400)) END "СЕКУНД_ХОДА",(SELECT MAX(j."СУММА") KEEP(DENSE_RANK LAST ORDER BY j."ID_ДЕЙСТВИЯ") FROM "ЖУРНАЛ_ДЕЙСТВИЙ" j WHERE j."ID_ИГРЫ"=g."ID_ИГРЫ" AND j."КОД_ДЕЙСТВИЯ"='БРОСОК_КУБИКА') "ПОСЛЕДНИЙ_КУБИК" FROM "УЧАСТНИКИ" me JOIN "ИГРЫ" g ON g."ID_ИГРЫ"=me."ID_ИГРЫ" JOIN "СТАТУСЫ_ИГР" sg ON sg."КОД_СТАТУСА_ИГРЫ"=g."КОД_СТАТУСА_ИГРЫ" LEFT JOIN "СОСТОЯНИЯ_ХОДА" sh ON sh."КОД_СОСТОЯНИЯ_ХОДА"=g."КОД_СОСТОЯНИЯ_ХОДА" WHERE me."ID_УЧАСТНИКА"=p_participant_id; RETURN rc; END;
 FUNCTION get_game_participants(p_participant_id NUMBER) RETURN SYS_REFCURSOR IS rc SYS_REFCURSOR; g NUMBER; BEGIN g:=participant_game(p_participant_id); OPEN rc FOR SELECT u."ID_УЧАСТНИКА",u."ID_ПОЛЬЗОВАТЕЛЯ",p."ЛОГИН",u."БАЛАНС",c."ПОЗИЦИЯ",c."НАЗВАНИЕ" "КЛЕТКА",u."ОЧЕРЕДЬ_ХОДА",u."КОД_СТАТУСА_УЧАСТНИКА",s."НАИМЕНОВАНИЕ" "СТАТУС",u."ГОТОВ",u."КОЛ_ТАЙМАУТОВ" FROM "УЧАСТНИКИ" u JOIN "ПОЛЬЗОВАТЕЛИ" p ON p."ID_ПОЛЬЗОВАТЕЛЯ"=u."ID_ПОЛЬЗОВАТЕЛЯ" JOIN "КЛЕТКИ" c ON c."ID_КЛЕТКИ"=u."ID_ПОЗИЦИИ" JOIN "СТАТУСЫ_УЧАСТНИКОВ" s ON s."КОД_СТАТУСА_УЧАСТНИКА"=u."КОД_СТАТУСА_УЧАСТНИКА" WHERE u."ID_ИГРЫ"=g ORDER BY NVL(u."ОЧЕРЕДЬ_ХОДА",99),u."ID_УЧАСТНИКА"; RETURN rc; END;
 FUNCTION get_board_state(p_participant_id NUMBER) RETURN SYS_REFCURSOR IS rc SYS_REFCURSOR; g NUMBER; BEGIN g:=participant_game(p_participant_id); OPEN rc FOR SELECT c."ID_КЛЕТКИ",c."ПОЗИЦИЯ",c."НАЗВАНИЕ",c."ТИП",c."ЦВЕТОВАЯ_ГРУППА",c."ЦЕНА_ПОКУПКИ",c."БАЗОВАЯ_РЕНТА",c."РЕНТА_1_ДОМ",c."РЕНТА_2_ДОМА",c."РЕНТА_ОТЕЛЬ",c."ЦЕНА_ДОМА",c."БОНУС_СТАРТА",v."ID_ВЛАДЕНИЯ",v."ID_ВЛАДЕЛЬЦА",op."ЛОГИН" "ВЛАДЕЛЕЦ",v."КОЛВО_ДОМОВ",v."ЗАЛОЖЕНА",CASE WHEN c."ТИП"='Улица' AND v."ID_ВЛАДЕЛЬЦА" IS NOT NULL AND(SELECT COUNT(*) FROM "ВЛАДЕНИЯ" vx JOIN "КЛЕТКИ" cx ON cx."ID_КЛЕТКИ"=vx."ID_КЛЕТКИ" WHERE vx."ID_ИГРЫ"=g AND vx."ID_ВЛАДЕЛЬЦА"=v."ID_ВЛАДЕЛЬЦА" AND vx."ЗАЛОЖЕНА"=0 AND cx."ЦВЕТОВАЯ_ГРУППА"=c."ЦВЕТОВАЯ_ГРУППА")=(SELECT COUNT(*) FROM "КЛЕТКИ" cg WHERE cg."ТИП"='Улица' AND cg."ЦВЕТОВАЯ_ГРУППА"=c."ЦВЕТОВАЯ_ГРУППА") THEN 2 ELSE 1 END "МНОЖИТЕЛЬ_ГРУППЫ" FROM "КЛЕТКИ" c LEFT JOIN "ВЛАДЕНИЯ" v ON v."ID_КЛЕТКИ"=c."ID_КЛЕТКИ" AND v."ID_ИГРЫ"=g LEFT JOIN "УЧАСТНИКИ" ou ON ou."ID_УЧАСТНИКА"=v."ID_ВЛАДЕЛЬЦА" LEFT JOIN "ПОЛЬЗОВАТЕЛИ" op ON op."ID_ПОЛЬЗОВАТЕЛЯ"=ou."ID_ПОЛЬЗОВАТЕЛЯ" ORDER BY c."ПОЗИЦИЯ"; RETURN rc; END;
 FUNCTION get_player_properties(p_participant_id NUMBER) RETURN SYS_REFCURSOR IS rc SYS_REFCURSOR; BEGIN OPEN rc FOR SELECT v."ID_ВЛАДЕНИЯ",c."ID_КЛЕТКИ",c."НАЗВАНИЕ",c."ТИП",v."КОЛВО_ДОМОВ",v."ЗАЛОЖЕНА",c."ЦЕНА_ПОКУПКИ",FLOOR(c."ЦЕНА_ПОКУПКИ"/2) "ЗАЛОГОВАЯ_СТОИМОСТЬ",FLOOR(NVL(CASE v."КОЛВО_ДОМОВ" WHEN 1 THEN c."РЕНТА_1_ДОМ" WHEN 2 THEN c."РЕНТА_2_ДОМА" WHEN 3 THEN c."РЕНТА_ОТЕЛЬ" END,0)/2) "СТОИМОСТЬ_ПРОДАЖИ_УРОВНЯ",CEIL(c."ЦЕНА_ПОКУПКИ"*(1+c_mortgage_interest)) "СТОИМОСТЬ_ВЫКУПА",CASE WHEN v."ЗАЛОЖЕНА"=0 AND v."КОЛВО_ДОМОВ"=0 THEN 1 ELSE 0 END "МОЖНО_ЗАЛОЖИТЬ" FROM "ВЛАДЕНИЯ" v JOIN "КЛЕТКИ" c ON c."ID_КЛЕТКИ"=v."ID_КЛЕТКИ" WHERE v."ID_ВЛАДЕЛЬЦА"=p_participant_id ORDER BY c."ПОЗИЦИЯ"; RETURN rc; END;
 FUNCTION get_active_auction(p_participant_id NUMBER) RETURN SYS_REFCURSOR IS rc SYS_REFCURSOR; g NUMBER; BEGIN g:=participant_game(p_participant_id); OPEN rc FOR SELECT a."ID_АУКЦИОНА",a."ID_КЛЕТКИ",c."НАЗВАНИЕ",a."СТАРТ_ЦЕНА",a."ДАТА_НАЧАЛА",s."ID_УЧАСТНИКА",p."ЛОГИН",s."СУММА",s."ДАТА_ВРЕМЯ" FROM "АУКЦИОНЫ" a JOIN "КЛЕТКИ" c ON c."ID_КЛЕТКИ"=a."ID_КЛЕТКИ" LEFT JOIN "СТАВКИ" s ON s."ID_АУКЦИОНА"=a."ID_АУКЦИОНА" LEFT JOIN "УЧАСТНИКИ" u ON u."ID_УЧАСТНИКА"=s."ID_УЧАСТНИКА" LEFT JOIN "ПОЛЬЗОВАТЕЛИ" p ON p."ID_ПОЛЬЗОВАТЕЛЯ"=u."ID_ПОЛЬЗОВАТЕЛЯ" WHERE a."ID_ИГРЫ"=g AND a."КОД_СТАТУСА_АУКЦИОНА"='АКТИВЕН' ORDER BY s."СУММА" DESC NULLS LAST,s."ДАТА_ВРЕМЯ"; RETURN rc; END;
 PROCEDURE roll_and_move(p_participant_id NUMBER,p_dice OUT NUMBER) IS g NUMBER; cur NUMBER; state VARCHAR2(40); gst VARCHAR2(40); bal NUMBER; pos NUMBER; np NUMBER; cell NUMBER; bonus NUMBER:=0; n NUMBER; BEGIN
  SELECT u."ID_ИГРЫ",x."ID_ТЕКУЩЕГО_УЧАСТНИКА",x."КОД_СОСТОЯНИЯ_ХОДА",x."КОД_СТАТУСА_ИГРЫ",u."БАЛАНС",c."ПОЗИЦИЯ" INTO g,cur,state,gst,bal,pos FROM "УЧАСТНИКИ" u JOIN "ИГРЫ" x ON x."ID_ИГРЫ"=u."ID_ИГРЫ" JOIN "КЛЕТКИ" c ON c."ID_КЛЕТКИ"=u."ID_ПОЗИЦИИ" WHERE u."ID_УЧАСТНИКА"=p_participant_id FOR UPDATE;
  IF gst<>'АКТИВНА' OR cur<>p_participant_id OR state<>'ОЖИДАНИЕ_БРОСКА' OR bal<0 THEN RAISE_APPLICATION_ERROR(-20060,'Бросок запрещён'); END IF; SELECT COUNT(*) INTO n FROM "АУКЦИОНЫ" WHERE "ID_ИГРЫ"=g AND "КОД_СТАТУСА_АУКЦИОНА"='АКТИВЕН'; IF n>0 THEN RAISE_APPLICATION_ERROR(-20061,'Идёт аукцион'); END IF; UPDATE "ИГРЫ" SET "ПОСЛЕДНЯЯ_КАРТА_ШАНСА"=NULL WHERE "ID_ИГРЫ"=g;
  p_dice:=TRUNC(DBMS_RANDOM.VALUE(1,7)); np:=MOD(pos-1+p_dice,12)+1; IF pos-1+p_dice>=12 THEN SELECT NVL("БОНУС_СТАРТА",50) INTO bonus FROM "КЛЕТКИ" WHERE "ПОЗИЦИЯ"=1; UPDATE "УЧАСТНИКИ" SET "БАЛАНС"="БАЛАНС"+bonus WHERE "ID_УЧАСТНИКА"=p_participant_id; END IF; SELECT "ID_КЛЕТКИ" INTO cell FROM "КЛЕТКИ" WHERE "ПОЗИЦИЯ"=np; UPDATE "УЧАСТНИКИ" SET "ID_ПОЗИЦИИ"=cell WHERE "ID_УЧАСТНИКА"=p_participant_id; add_action(g,p_participant_id,NULL,'БРОСОК_КУБИКА',p_dice); add_action(g,p_participant_id,cell,'ПОСЕЩЕНИЕ_КЛЕТКИ',NULL); IF bonus>0 THEN add_action(g,p_participant_id,cell,'БОНУС_СТАРТА',bonus); END IF; process_cell(p_participant_id,p_dice);
 END;
 PROCEDURE process_cell(p_participant_id NUMBER,p_dice NUMBER) IS g NUMBER; cell NUMBER; typ VARCHAR2(30); grp VARCHAR2(20); owner NUMBER; mort NUMBER; lvl NUMBER; BEGIN
  SELECT u."ID_ИГРЫ",u."ID_ПОЗИЦИИ",c."ТИП",c."ЦВЕТОВАЯ_ГРУППА" INTO g,cell,typ,grp FROM "УЧАСТНИКИ" u JOIN "КЛЕТКИ" c ON c."ID_КЛЕТКИ"=u."ID_ПОЗИЦИИ" WHERE u."ID_УЧАСТНИКА"=p_participant_id;
  IF typ='Старт' THEN UPDATE "ИГРЫ" SET "КОД_СОСТОЯНИЯ_ХОДА"='ЗАВЕРШЕНИЕ_ХОДА' WHERE "ID_ИГРЫ"=g;
  ELSIF typ='Шанс' THEN apply_chance(p_participant_id,p_dice);
  ELSE SELECT "ID_ВЛАДЕЛЬЦА","ЗАЛОЖЕНА","КОЛВО_ДОМОВ" INTO owner,mort,lvl FROM "ВЛАДЕНИЯ" WHERE "ID_ИГРЫ"=g AND "ID_КЛЕТКИ"=cell; IF owner IS NULL THEN UPDATE "ИГРЫ" SET "КОД_СОСТОЯНИЯ_ХОДА"='ОЖИДАНИЕ_ПОКУПКИ' WHERE "ID_ИГРЫ"=g; ELSIF owner<>p_participant_id THEN IF mort=1 THEN UPDATE "ИГРЫ" SET "КОД_СОСТОЯНИЯ_ХОДА"='ЗАВЕРШЕНИЕ_ХОДА' WHERE "ID_ИГРЫ"=g; ELSE pay_rent(p_participant_id,cell,p_dice); END IF; ELSE IF typ='Улица' AND mort=0 AND lvl<3 THEN UPDATE "ИГРЫ" SET "КОД_СОСТОЯНИЯ_ХОДА"='ОЖИДАНИЕ_УЛУЧШЕНИЯ' WHERE "ID_ИГРЫ"=g; ELSE UPDATE "ИГРЫ" SET "КОД_СОСТОЯНИЯ_ХОДА"='ЗАВЕРШЕНИЕ_ХОДА' WHERE "ID_ИГРЫ"=g; END IF; END IF; END IF;
 END;
 PROCEDURE advance_to_next_player(p_game_id NUMBER) IS cur NUMBER; ord NUMBER; nxt NUMBER; BEGIN SELECT "ID_ТЕКУЩЕГО_УЧАСТНИКА" INTO cur FROM "ИГРЫ" WHERE "ID_ИГРЫ"=p_game_id FOR UPDATE; SELECT "ОЧЕРЕДЬ_ХОДА" INTO ord FROM "УЧАСТНИКИ" WHERE "ID_УЧАСТНИКА"=cur; BEGIN SELECT "ID_УЧАСТНИКА" INTO nxt FROM(SELECT "ID_УЧАСТНИКА" FROM "УЧАСТНИКИ" WHERE "ID_ИГРЫ"=p_game_id AND "КОД_СТАТУСА_УЧАСТНИКА"='АКТИВЕН' AND "ОЧЕРЕДЬ_ХОДА">ord ORDER BY "ОЧЕРЕДЬ_ХОДА") WHERE ROWNUM=1; EXCEPTION WHEN NO_DATA_FOUND THEN SELECT "ID_УЧАСТНИКА" INTO nxt FROM(SELECT "ID_УЧАСТНИКА" FROM "УЧАСТНИКИ" WHERE "ID_ИГРЫ"=p_game_id AND "КОД_СТАТУСА_УЧАСТНИКА"='АКТИВЕН' ORDER BY "ОЧЕРЕДЬ_ХОДА") WHERE ROWNUM=1; END; UPDATE "ИГРЫ" SET "ID_ТЕКУЩЕГО_УЧАСТНИКА"=nxt,"ВРЕМЯ_НАЧАЛА_ХОДА"=SYSDATE,"КОД_СОСТОЯНИЯ_ХОДА"='ОЖИДАНИЕ_БРОСКА' WHERE "ID_ИГРЫ"=p_game_id; END;
 PROCEDURE end_turn(p_game_id NUMBER) IS state VARCHAR2(40); cur NUMBER; bal NUMBER; n NUMBER; st VARCHAR2(40); BEGIN SELECT "КОД_СОСТОЯНИЯ_ХОДА","ID_ТЕКУЩЕГО_УЧАСТНИКА" INTO state,cur FROM "ИГРЫ" WHERE "ID_ИГРЫ"=p_game_id FOR UPDATE; IF state<>'ЗАВЕРШЕНИЕ_ХОДА' THEN RAISE_APPLICATION_ERROR(-20062,'Ход не завершён'); END IF; SELECT "БАЛАНС" INTO bal FROM "УЧАСТНИКИ" WHERE "ID_УЧАСТНИКА"=cur FOR UPDATE; IF bal<0 THEN RAISE_APPLICATION_ERROR(-20063,'Сначала покройте долг'); END IF; SELECT COUNT(*) INTO n FROM "АУКЦИОНЫ" WHERE "ID_ИГРЫ"=p_game_id AND "КОД_СТАТУСА_АУКЦИОНА"='АКТИВЕН'; IF n>0 THEN RAISE_APPLICATION_ERROR(-20064,'Аукцион не завершён'); END IF; finish_or_continue(p_game_id); SELECT "КОД_СТАТУСА_ИГРЫ" INTO st FROM "ИГРЫ" WHERE "ID_ИГРЫ"=p_game_id; IF st='АКТИВНА' THEN advance_to_next_player(p_game_id); END IF; END;

 PROCEDURE buy_property(p_participant_id NUMBER,p_cell_id NUMBER) IS g NUMBER; cur NUMBER; state VARCHAR2(40); owner NUMBER; price NUMBER; bal NUMBER; typ VARCHAR2(30); BEGIN SELECT u."ID_ИГРЫ",x."ID_ТЕКУЩЕГО_УЧАСТНИКА",x."КОД_СОСТОЯНИЯ_ХОДА",u."БАЛАНС" INTO g,cur,state,bal FROM "УЧАСТНИКИ" u JOIN "ИГРЫ" x ON x."ID_ИГРЫ"=u."ID_ИГРЫ" WHERE u."ID_УЧАСТНИКА"=p_participant_id FOR UPDATE; IF cur<>p_participant_id OR state<>'ОЖИДАНИЕ_ПОКУПКИ' THEN RAISE_APPLICATION_ERROR(-20070,'Покупка недоступна'); END IF; SELECT v."ID_ВЛАДЕЛЬЦА",c."ЦЕНА_ПОКУПКИ",c."ТИП" INTO owner,price,typ FROM "ВЛАДЕНИЯ" v JOIN "КЛЕТКИ" c ON c."ID_КЛЕТКИ"=v."ID_КЛЕТКИ" WHERE v."ID_ИГРЫ"=g AND v."ID_КЛЕТКИ"=p_cell_id FOR UPDATE; IF owner IS NOT NULL OR typ NOT IN('Улица','Коммунальная') OR bal<price THEN RAISE_APPLICATION_ERROR(-20071,'Клетку нельзя купить'); END IF; UPDATE "УЧАСТНИКИ" SET "БАЛАНС"="БАЛАНС"-price WHERE "ID_УЧАСТНИКА"=p_participant_id; UPDATE "ВЛАДЕНИЯ" SET "ID_ВЛАДЕЛЬЦА"=p_participant_id WHERE "ID_ИГРЫ"=g AND "ID_КЛЕТКИ"=p_cell_id; add_action(g,p_participant_id,p_cell_id,'ПОКУПКА_СОБСТВЕННОСТИ',price); UPDATE "ИГРЫ" SET "КОД_СОСТОЯНИЯ_ХОДА"='ЗАВЕРШЕНИЕ_ХОДА' WHERE "ID_ИГРЫ"=g; END;
 PROCEDURE decline_purchase(p_participant_id NUMBER,p_cell_id NUMBER) IS g NUMBER; cur NUMBER; state VARCHAR2(40); owner NUMBER; BEGIN SELECT u."ID_ИГРЫ",x."ID_ТЕКУЩЕГО_УЧАСТНИКА",x."КОД_СОСТОЯНИЯ_ХОДА" INTO g,cur,state FROM "УЧАСТНИКИ" u JOIN "ИГРЫ" x ON x."ID_ИГРЫ"=u."ID_ИГРЫ" WHERE u."ID_УЧАСТНИКА"=p_participant_id FOR UPDATE; IF cur<>p_participant_id OR state<>'ОЖИДАНИЕ_ПОКУПКИ' THEN RAISE_APPLICATION_ERROR(-20073,'Отказ недоступен'); END IF; SELECT "ID_ВЛАДЕЛЬЦА" INTO owner FROM "ВЛАДЕНИЯ" WHERE "ID_ИГРЫ"=g AND "ID_КЛЕТКИ"=p_cell_id FOR UPDATE; IF owner IS NOT NULL THEN RAISE_APPLICATION_ERROR(-20074,'Клетка уже куплена'); END IF; add_action(g,p_participant_id,p_cell_id,'ОТКАЗ_ОТ_ПОКУПКИ',NULL); start_auction(g,p_cell_id); END;
 FUNCTION calculate_rent(p_ownership_id NUMBER,p_dice NUMBER) RETURN NUMBER IS typ VARCHAR2(30); grp VARCHAR2(20); mort NUMBER; lvl NUMBER; rent NUMBER; owner NUMBER; g NUMBER; n NUMBER; totaln NUMBER; BEGIN SELECT c."ТИП",c."ЦВЕТОВАЯ_ГРУППА",v."ЗАЛОЖЕНА",v."КОЛВО_ДОМОВ",v."ID_ВЛАДЕЛЬЦА",v."ID_ИГРЫ",CASE v."КОЛВО_ДОМОВ" WHEN 0 THEN c."БАЗОВАЯ_РЕНТА" WHEN 1 THEN c."РЕНТА_1_ДОМ" WHEN 2 THEN c."РЕНТА_2_ДОМА" WHEN 3 THEN c."РЕНТА_ОТЕЛЬ" END INTO typ,grp,mort,lvl,owner,g,rent FROM "ВЛАДЕНИЯ" v JOIN "КЛЕТКИ" c ON c."ID_КЛЕТКИ"=v."ID_КЛЕТКИ" WHERE v."ID_ВЛАДЕНИЯ"=p_ownership_id; IF mort=1 THEN RETURN 0; END IF; IF typ='Коммунальная' THEN SELECT COUNT(*) INTO n FROM "ВЛАДЕНИЯ" v JOIN "КЛЕТКИ" c ON c."ID_КЛЕТКИ"=v."ID_КЛЕТКИ" WHERE v."ID_ИГРЫ"=g AND v."ID_ВЛАДЕЛЬЦА"=owner AND v."ЗАЛОЖЕНА"=0 AND c."ТИП"='Коммунальная'; RETURN p_dice*CASE WHEN n>=2 THEN 50 ELSE 25 END; END IF; SELECT COUNT(*) INTO totaln FROM "КЛЕТКИ" WHERE "ТИП"='Улица' AND "ЦВЕТОВАЯ_ГРУППА"=grp; SELECT COUNT(*) INTO n FROM "ВЛАДЕНИЯ" v JOIN "КЛЕТКИ" c ON c."ID_КЛЕТКИ"=v."ID_КЛЕТКИ" WHERE v."ID_ИГРЫ"=g AND v."ID_ВЛАДЕЛЬЦА"=owner AND v."ЗАЛОЖЕНА"=0 AND c."ТИП"='Улица' AND c."ЦВЕТОВАЯ_ГРУППА"=grp; RETURN NVL(rent,0)*CASE WHEN totaln>0 AND n=totaln THEN 2 ELSE 1 END; END;
 PROCEDURE pay_rent(p_participant_id NUMBER,p_cell_id NUMBER,p_dice NUMBER) IS g NUMBER; oid NUMBER; owner NUMBER; mort NUMBER; rent NUMBER; bal NUMBER; BEGIN g:=participant_game(p_participant_id); SELECT "ID_ВЛАДЕНИЯ","ID_ВЛАДЕЛЬЦА","ЗАЛОЖЕНА" INTO oid,owner,mort FROM "ВЛАДЕНИЯ" WHERE "ID_ИГРЫ"=g AND "ID_КЛЕТКИ"=p_cell_id FOR UPDATE; IF owner IS NULL OR owner=p_participant_id OR mort=1 THEN RAISE_APPLICATION_ERROR(-20075,'Аренда не требуется'); END IF; rent:=calculate_rent(oid,p_dice); UPDATE "УЧАСТНИКИ" SET "БАЛАНС"="БАЛАНС"-rent WHERE "ID_УЧАСТНИКА"=p_participant_id; UPDATE "УЧАСТНИКИ" SET "БАЛАНС"="БАЛАНС"+rent WHERE "ID_УЧАСТНИКА"=owner; SELECT "БАЛАНС" INTO bal FROM "УЧАСТНИКИ" WHERE "ID_УЧАСТНИКА"=p_participant_id; add_action(g,p_participant_id,p_cell_id,'ОПЛАТА_АРЕНДЫ',rent); IF bal<0 THEN UPDATE "ИГРЫ" SET "КОД_СОСТОЯНИЯ_ХОДА"='ПОКРЫТИЕ_ДОЛГА',"ВРЕМЯ_НАЧАЛА_ХОДА"=SYSDATE WHERE "ID_ИГРЫ"=g; ELSE UPDATE "ИГРЫ" SET "КОД_СОСТОЯНИЯ_ХОДА"='ЗАВЕРШЕНИЕ_ХОДА' WHERE "ID_ИГРЫ"=g; END IF; END;
 PROCEDURE apply_chance(p_participant_id NUMBER,p_dice NUMBER) IS g NUMBER; cid NUMBER; target NUMBER; typ "КАРТЫ_ШАНСА"."ТИП_ЭФФЕКТА"%TYPE; amt NUMBER; txt "КАРТЫ_ШАНСА"."ТЕКСТ_СОБЫТИЯ"%TYPE; chance_cell NUMBER; oldpos NUMBER; newpos NUMBER; bal NUMBER; bonus NUMBER; BEGIN
  g:=participant_game(p_participant_id); SELECT "ID_ПОЗИЦИИ" INTO chance_cell FROM "УЧАСТНИКИ" WHERE "ID_УЧАСТНИКА"=p_participant_id;
  SELECT "ID_КАРТЫ","ID_ЦЕЛЕВОЙ_КЛЕТКИ","ТИП_ЭФФЕКТА","СУММА_ИЗМЕНЕНИЯ","ТЕКСТ_СОБЫТИЯ" INTO cid,target,typ,amt,txt FROM(SELECT "ID_КАРТЫ","ID_ЦЕЛЕВОЙ_КЛЕТКИ","ТИП_ЭФФЕКТА","СУММА_ИЗМЕНЕНИЯ","ТЕКСТ_СОБЫТИЯ" FROM "КАРТЫ_ШАНСА" ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM=1;
  UPDATE "ИГРЫ" SET "ПОСЛЕДНЯЯ_КАРТА_ШАНСА"=txt WHERE "ID_ИГРЫ"=g;
  add_action(g,p_participant_id,chance_cell,'КАРТА_ШАНСА',amt);
  IF typ='Премия' THEN UPDATE "УЧАСТНИКИ" SET "БАЛАНС"="БАЛАНС"+amt WHERE "ID_УЧАСТНИКА"=p_participant_id; UPDATE "ИГРЫ" SET "КОД_СОСТОЯНИЯ_ХОДА"='ЗАВЕРШЕНИЕ_ХОДА' WHERE "ID_ИГРЫ"=g;
  ELSIF typ='Штраф' THEN UPDATE "УЧАСТНИКИ" SET "БАЛАНС"="БАЛАНС"-amt WHERE "ID_УЧАСТНИКА"=p_participant_id; SELECT "БАЛАНС" INTO bal FROM "УЧАСТНИКИ" WHERE "ID_УЧАСТНИКА"=p_participant_id; IF bal<0 THEN UPDATE "ИГРЫ" SET "КОД_СОСТОЯНИЯ_ХОДА"='ПОКРЫТИЕ_ДОЛГА',"ВРЕМЯ_НАЧАЛА_ХОДА"=SYSDATE WHERE "ID_ИГРЫ"=g; ELSE UPDATE "ИГРЫ" SET "КОД_СОСТОЯНИЯ_ХОДА"='ЗАВЕРШЕНИЕ_ХОДА' WHERE "ID_ИГРЫ"=g; END IF;
  ELSE SELECT c."ПОЗИЦИЯ" INTO oldpos FROM "УЧАСТНИКИ" u JOIN "КЛЕТКИ" c ON c."ID_КЛЕТКИ"=u."ID_ПОЗИЦИИ" WHERE u."ID_УЧАСТНИКА"=p_participant_id; SELECT "ПОЗИЦИЯ" INTO newpos FROM "КЛЕТКИ" WHERE "ID_КЛЕТКИ"=target; IF newpos<=oldpos THEN SELECT NVL("БОНУС_СТАРТА",50) INTO bonus FROM "КЛЕТКИ" WHERE "ПОЗИЦИЯ"=1; UPDATE "УЧАСТНИКИ" SET "БАЛАНС"="БАЛАНС"+bonus WHERE "ID_УЧАСТНИКА"=p_participant_id; add_action(g,p_participant_id,target,'БОНУС_СТАРТА',bonus); END IF; UPDATE "УЧАСТНИКИ" SET "ID_ПОЗИЦИИ"=target WHERE "ID_УЧАСТНИКА"=p_participant_id; add_action(g,p_participant_id,target,'ПОСЕЩЕНИЕ_КЛЕТКИ',NULL); process_cell(p_participant_id,p_dice); END IF;
 END;
 FUNCTION owns_full_color_group(p_participant_id NUMBER,p_color_group VARCHAR2) RETURN NUMBER IS g NUMBER; totaln NUMBER; owned NUMBER; BEGIN g:=participant_game(p_participant_id); SELECT COUNT(*) INTO totaln FROM "КЛЕТКИ" WHERE "ТИП"='Улица' AND "ЦВЕТОВАЯ_ГРУППА"=p_color_group; SELECT COUNT(*) INTO owned FROM "ВЛАДЕНИЯ" v JOIN "КЛЕТКИ" c ON c."ID_КЛЕТКИ"=v."ID_КЛЕТКИ" WHERE v."ID_ИГРЫ"=g AND c."ЦВЕТОВАЯ_ГРУППА"=p_color_group AND c."ТИП"='Улица' AND v."ID_ВЛАДЕЛЬЦА"=p_participant_id AND v."ЗАЛОЖЕНА"=0; RETURN CASE WHEN totaln>0 AND totaln=owned THEN 1 ELSE 0 END; END;
 PROCEDURE build_house(p_participant_id NUMBER,p_cell_id NUMBER) IS g NUMBER; cur NUMBER; state VARCHAR2(40); typ VARCHAR2(30); owner NUMBER; mort NUMBER; lvl NUMBER; price NUMBER; bal NUMBER; BEGIN SELECT u."ID_ИГРЫ",x."ID_ТЕКУЩЕГО_УЧАСТНИКА",x."КОД_СОСТОЯНИЯ_ХОДА",u."БАЛАНС" INTO g,cur,state,bal FROM "УЧАСТНИКИ" u JOIN "ИГРЫ" x ON x."ID_ИГРЫ"=u."ID_ИГРЫ" WHERE u."ID_УЧАСТНИКА"=p_participant_id FOR UPDATE; SELECT c."ТИП",CASE v."КОЛВО_ДОМОВ" WHEN 0 THEN c."РЕНТА_1_ДОМ" WHEN 1 THEN c."РЕНТА_2_ДОМА" WHEN 2 THEN c."РЕНТА_ОТЕЛЬ" END,v."ID_ВЛАДЕЛЬЦА",v."ЗАЛОЖЕНА",v."КОЛВО_ДОМОВ" INTO typ,price,owner,mort,lvl FROM "ВЛАДЕНИЯ" v JOIN "КЛЕТКИ" c ON c."ID_КЛЕТКИ"=v."ID_КЛЕТКИ" WHERE v."ID_ИГРЫ"=g AND v."ID_КЛЕТКИ"=p_cell_id FOR UPDATE; IF cur<>p_participant_id OR state<>'ОЖИДАНИЕ_УЛУЧШЕНИЯ' OR typ<>'Улица' OR owner<>p_participant_id OR mort<>0 OR lvl>=3 OR bal<price THEN RAISE_APPLICATION_ERROR(-20080,'Для следующего улучшения недостаточно денег или оно недоступно'); END IF; UPDATE "УЧАСТНИКИ" SET "БАЛАНС"="БАЛАНС"-price WHERE "ID_УЧАСТНИКА"=p_participant_id; UPDATE "ВЛАДЕНИЯ" SET "КОЛВО_ДОМОВ"="КОЛВО_ДОМОВ"+1 WHERE "ID_ИГРЫ"=g AND "ID_КЛЕТКИ"=p_cell_id; add_action(g,p_participant_id,p_cell_id,'ПОКУПКА_УЛУЧШЕНИЯ',price); UPDATE "ИГРЫ" SET "КОД_СОСТОЯНИЯ_ХОДА"='ЗАВЕРШЕНИЕ_ХОДА' WHERE "ID_ИГРЫ"=g; END;
 PROCEDURE decline_improvement(p_participant_id NUMBER,p_cell_id NUMBER) IS g NUMBER; cur NUMBER; state VARCHAR2(40); owner NUMBER; BEGIN SELECT u."ID_ИГРЫ",x."ID_ТЕКУЩЕГО_УЧАСТНИКА",x."КОД_СОСТОЯНИЯ_ХОДА" INTO g,cur,state FROM "УЧАСТНИКИ" u JOIN "ИГРЫ" x ON x."ID_ИГРЫ"=u."ID_ИГРЫ" WHERE u."ID_УЧАСТНИКА"=p_participant_id; SELECT "ID_ВЛАДЕЛЬЦА" INTO owner FROM "ВЛАДЕНИЯ" WHERE "ID_ИГРЫ"=g AND "ID_КЛЕТКИ"=p_cell_id; IF cur<>p_participant_id OR state<>'ОЖИДАНИЕ_УЛУЧШЕНИЯ' OR owner<>p_participant_id THEN RAISE_APPLICATION_ERROR(-20081,'Отказ недоступен'); END IF; add_action(g,p_participant_id,p_cell_id,'ОТКАЗ_ОТ_УЛУЧШЕНИЯ',NULL); UPDATE "ИГРЫ" SET "КОД_СОСТОЯНИЯ_ХОДА"='ЗАВЕРШЕНИЕ_ХОДА' WHERE "ID_ИГРЫ"=g; END;
 PROCEDURE sell_buildings(p_participant_id NUMBER,p_ownership_id NUMBER,p_count NUMBER) IS g NUMBER; cur NUMBER; state VARCHAR2(40); cell NUMBER; owner NUMBER; lvl NUMBER; mort NUMBER; price NUMBER; typ VARCHAR2(30); amount NUMBER; bal NUMBER; BEGIN SELECT u."ID_ИГРЫ",x."ID_ТЕКУЩЕГО_УЧАСТНИКА",x."КОД_СОСТОЯНИЯ_ХОДА" INTO g,cur,state FROM "УЧАСТНИКИ" u JOIN "ИГРЫ" x ON x."ID_ИГРЫ"=u."ID_ИГРЫ" WHERE u."ID_УЧАСТНИКА"=p_participant_id FOR UPDATE; IF cur<>p_participant_id OR state NOT IN('ОЖИДАНИЕ_БРОСКА','ПОКРЫТИЕ_ДОЛГА') THEN RAISE_APPLICATION_ERROR(-20082,'Продажа недоступна'); END IF; SELECT v."ID_КЛЕТКИ",v."ID_ВЛАДЕЛЬЦА",v."КОЛВО_ДОМОВ",v."ЗАЛОЖЕНА",CASE v."КОЛВО_ДОМОВ" WHEN 1 THEN c."РЕНТА_1_ДОМ" WHEN 2 THEN c."РЕНТА_2_ДОМА" WHEN 3 THEN c."РЕНТА_ОТЕЛЬ" END,c."ТИП" INTO cell,owner,lvl,mort,price,typ FROM "ВЛАДЕНИЯ" v JOIN "КЛЕТКИ" c ON c."ID_КЛЕТКИ"=v."ID_КЛЕТКИ" WHERE v."ID_ВЛАДЕНИЯ"=p_ownership_id AND v."ID_ИГРЫ"=g FOR UPDATE; IF owner<>p_participant_id OR typ<>'Улица' OR mort<>0 OR p_count<>1 OR lvl<1 THEN RAISE_APPLICATION_ERROR(-20083,'За одно действие продаётся один текущий уровень'); END IF; amount:=FLOOR(price/2); UPDATE "ВЛАДЕНИЯ" SET "КОЛВО_ДОМОВ"="КОЛВО_ДОМОВ"-1 WHERE "ID_ВЛАДЕНИЯ"=p_ownership_id; UPDATE "УЧАСТНИКИ" SET "БАЛАНС"="БАЛАНС"+amount WHERE "ID_УЧАСТНИКА"=p_participant_id; add_action(g,p_participant_id,cell,'ПРОДАЖА_ПОСТРОЕК',amount); IF state='ПОКРЫТИЕ_ДОЛГА' THEN SELECT "БАЛАНС" INTO bal FROM "УЧАСТНИКИ" WHERE "ID_УЧАСТНИКА"=p_participant_id; IF bal>=0 THEN UPDATE "ИГРЫ" SET "КОД_СОСТОЯНИЯ_ХОДА"='ЗАВЕРШЕНИЕ_ХОДА' WHERE "ID_ИГРЫ"=g; END IF; END IF; END;
 PROCEDURE mortgage_properties(p_participant_id NUMBER,p_ownership_ids number_list) IS g NUMBER; cur NUMBER; state VARCHAR2(40); total NUMBER:=0; n NUMBER; bal NUMBER; BEGIN IF p_ownership_ids IS NULL OR p_ownership_ids.COUNT=0 THEN RAISE_APPLICATION_ERROR(-20084,'Список пуст'); END IF; SELECT u."ID_ИГРЫ",x."ID_ТЕКУЩЕГО_УЧАСТНИКА",x."КОД_СОСТОЯНИЯ_ХОДА" INTO g,cur,state FROM "УЧАСТНИКИ" u JOIN "ИГРЫ" x ON x."ID_ИГРЫ"=u."ID_ИГРЫ" WHERE u."ID_УЧАСТНИКА"=p_participant_id FOR UPDATE; IF cur<>p_participant_id OR state<>'ПОКРЫТИЕ_ДОЛГА' THEN RAISE_APPLICATION_ERROR(-20085,'Залог разрешён только для покрытия отрицательного баланса'); END IF; SELECT COUNT(*),NVL(SUM(FLOOR(c."ЦЕНА_ПОКУПКИ"/2)),0) INTO n,total FROM "ВЛАДЕНИЯ" v JOIN "КЛЕТКИ" c ON c."ID_КЛЕТКИ"=v."ID_КЛЕТКИ" WHERE v."ID_ВЛАДЕНИЯ" IN(SELECT COLUMN_VALUE FROM TABLE(p_ownership_ids)) AND v."ID_ИГРЫ"=g AND v."ID_ВЛАДЕЛЬЦА"=p_participant_id AND v."ЗАЛОЖЕНА"=0 AND v."КОЛВО_ДОМОВ"=0; IF n<>p_ownership_ids.COUNT THEN RAISE_APPLICATION_ERROR(-20086,'Некоторые объекты нельзя заложить'); END IF; FOR r IN(SELECT v."ID_ВЛАДЕНИЯ" oid,v."ID_КЛЕТКИ" cell,FLOOR(c."ЦЕНА_ПОКУПКИ"/2) amount FROM "ВЛАДЕНИЯ" v JOIN "КЛЕТКИ" c ON c."ID_КЛЕТКИ"=v."ID_КЛЕТКИ" WHERE v."ID_ВЛАДЕНИЯ" IN(SELECT COLUMN_VALUE FROM TABLE(p_ownership_ids))) LOOP UPDATE "ВЛАДЕНИЯ" SET "ЗАЛОЖЕНА"=1 WHERE "ID_ВЛАДЕНИЯ"=r.oid; add_action(g,p_participant_id,r.cell,'ЗАЛОГ_СОБСТВЕННОСТИ',r.amount); END LOOP; UPDATE "УЧАСТНИКИ" SET "БАЛАНС"="БАЛАНС"+total WHERE "ID_УЧАСТНИКА"=p_participant_id; SELECT "БАЛАНС" INTO bal FROM "УЧАСТНИКИ" WHERE "ID_УЧАСТНИКА"=p_participant_id; IF bal>=0 THEN UPDATE "ИГРЫ" SET "КОД_СОСТОЯНИЯ_ХОДА"='ЗАВЕРШЕНИЕ_ХОДА' WHERE "ID_ИГРЫ"=g; END IF; END;
 PROCEDURE resolve_debt(p_participant_id NUMBER,p_mortgage_ids number_list,p_sale_ids number_list) IS g NUMBER; cur NUMBER; state VARCHAR2(40); total NUMBER:=0; n NUMBER; bal NUMBER; mc NUMBER:=0; sc NUMBER:=0; BEGIN SELECT u."ID_ИГРЫ",x."ID_ТЕКУЩЕГО_УЧАСТНИКА",x."КОД_СОСТОЯНИЯ_ХОДА" INTO g,cur,state FROM "УЧАСТНИКИ" u JOIN "ИГРЫ" x ON x."ID_ИГРЫ"=u."ID_ИГРЫ" WHERE u."ID_УЧАСТНИКА"=p_participant_id FOR UPDATE; IF cur<>p_participant_id OR state<>'ПОКРЫТИЕ_ДОЛГА' THEN RAISE_APPLICATION_ERROR(-20120,'Управление долгом сейчас недоступно'); END IF; IF p_mortgage_ids IS NOT NULL THEN mc:=p_mortgage_ids.COUNT; END IF; IF p_sale_ids IS NOT NULL THEN sc:=p_sale_ids.COUNT; END IF; IF mc+sc=0 THEN RAISE_APPLICATION_ERROR(-20121,'Ничего не выбрано'); END IF; IF mc>0 THEN SELECT COUNT(*),NVL(SUM(FLOOR(c."ЦЕНА_ПОКУПКИ"/2)),0) INTO n,total FROM "ВЛАДЕНИЯ" v JOIN "КЛЕТКИ" c ON c."ID_КЛЕТКИ"=v."ID_КЛЕТКИ" WHERE v."ID_ВЛАДЕНИЯ" IN(SELECT COLUMN_VALUE FROM TABLE(p_mortgage_ids)) AND v."ID_ИГРЫ"=g AND v."ID_ВЛАДЕЛЬЦА"=p_participant_id AND v."ЗАЛОЖЕНА"=0 AND v."КОЛВО_ДОМОВ"=0; IF n<>mc THEN RAISE_APPLICATION_ERROR(-20122,'Некоторые объекты нельзя заложить'); END IF; END IF; IF sc>0 THEN SELECT COUNT(*),total+NVL(SUM(FLOOR(CASE v."КОЛВО_ДОМОВ" WHEN 1 THEN c."РЕНТА_1_ДОМ" WHEN 2 THEN c."РЕНТА_2_ДОМА" WHEN 3 THEN c."РЕНТА_ОТЕЛЬ" END/2)),0) INTO n,total FROM "ВЛАДЕНИЯ" v JOIN "КЛЕТКИ" c ON c."ID_КЛЕТКИ"=v."ID_КЛЕТКИ" WHERE v."ID_ВЛАДЕНИЯ" IN(SELECT COLUMN_VALUE FROM TABLE(p_sale_ids)) AND v."ID_ИГРЫ"=g AND v."ID_ВЛАДЕЛЬЦА"=p_participant_id AND v."ЗАЛОЖЕНА"=0 AND v."КОЛВО_ДОМОВ">0 AND c."ТИП"='Улица'; IF n<>sc THEN RAISE_APPLICATION_ERROR(-20123,'Некоторые постройки нельзя продать'); END IF; END IF; IF mc>0 THEN FOR r IN(SELECT v."ID_ВЛАДЕНИЯ" oid,v."ID_КЛЕТКИ" cell,FLOOR(c."ЦЕНА_ПОКУПКИ"/2) amount FROM "ВЛАДЕНИЯ" v JOIN "КЛЕТКИ" c ON c."ID_КЛЕТКИ"=v."ID_КЛЕТКИ" WHERE v."ID_ВЛАДЕНИЯ" IN(SELECT COLUMN_VALUE FROM TABLE(p_mortgage_ids))) LOOP UPDATE "ВЛАДЕНИЯ" SET "ЗАЛОЖЕНА"=1 WHERE "ID_ВЛАДЕНИЯ"=r.oid; add_action(g,p_participant_id,r.cell,'ЗАЛОГ_СОБСТВЕННОСТИ',r.amount); END LOOP; END IF; IF sc>0 THEN FOR r IN(SELECT v."ID_ВЛАДЕНИЯ" oid,v."ID_КЛЕТКИ" cell,FLOOR(CASE v."КОЛВО_ДОМОВ" WHEN 1 THEN c."РЕНТА_1_ДОМ" WHEN 2 THEN c."РЕНТА_2_ДОМА" WHEN 3 THEN c."РЕНТА_ОТЕЛЬ" END/2) amount FROM "ВЛАДЕНИЯ" v JOIN "КЛЕТКИ" c ON c."ID_КЛЕТКИ"=v."ID_КЛЕТКИ" WHERE v."ID_ВЛАДЕНИЯ" IN(SELECT COLUMN_VALUE FROM TABLE(p_sale_ids))) LOOP UPDATE "ВЛАДЕНИЯ" SET "КОЛВО_ДОМОВ"="КОЛВО_ДОМОВ"-1 WHERE "ID_ВЛАДЕНИЯ"=r.oid; add_action(g,p_participant_id,r.cell,'ПРОДАЖА_ПОСТРОЕК',r.amount); END LOOP; END IF; UPDATE "УЧАСТНИКИ" SET "БАЛАНС"="БАЛАНС"+total WHERE "ID_УЧАСТНИКА"=p_participant_id; SELECT "БАЛАНС" INTO bal FROM "УЧАСТНИКИ" WHERE "ID_УЧАСТНИКА"=p_participant_id; IF bal>=0 THEN UPDATE "ИГРЫ" SET "КОД_СОСТОЯНИЯ_ХОДА"='ЗАВЕРШЕНИЕ_ХОДА' WHERE "ID_ИГРЫ"=g; END IF; END;
 PROCEDURE redeem_property(p_participant_id NUMBER,p_ownership_id NUMBER) IS g NUMBER; cur NUMBER; state VARCHAR2(40); owner NUMBER; mort NUMBER; price NUMBER; cell NUMBER; bal NUMBER; amount NUMBER; n NUMBER; BEGIN SELECT u."ID_ИГРЫ",x."ID_ТЕКУЩЕГО_УЧАСТНИКА",x."КОД_СОСТОЯНИЯ_ХОДА",u."БАЛАНС" INTO g,cur,state,bal FROM "УЧАСТНИКИ" u JOIN "ИГРЫ" x ON x."ID_ИГРЫ"=u."ID_ИГРЫ" WHERE u."ID_УЧАСТНИКА"=p_participant_id FOR UPDATE; IF cur<>p_participant_id OR state<>'ОЖИДАНИЕ_БРОСКА' OR bal<0 THEN RAISE_APPLICATION_ERROR(-20087,'Снятие залога недоступно'); END IF; SELECT COUNT(*) INTO n FROM "АУКЦИОНЫ" WHERE "ID_ИГРЫ"=g AND "КОД_СТАТУСА_АУКЦИОНА"='АКТИВЕН'; IF n>0 THEN RAISE_APPLICATION_ERROR(-20088,'Идёт аукцион'); END IF; SELECT v."ID_ВЛАДЕЛЬЦА",v."ЗАЛОЖЕНА",c."ЦЕНА_ПОКУПКИ",v."ID_КЛЕТКИ" INTO owner,mort,price,cell FROM "ВЛАДЕНИЯ" v JOIN "КЛЕТКИ" c ON c."ID_КЛЕТКИ"=v."ID_КЛЕТКИ" WHERE v."ID_ВЛАДЕНИЯ"=p_ownership_id AND v."ID_ИГРЫ"=g FOR UPDATE; amount:=CEIL(price*(1+c_mortgage_interest)); IF owner<>p_participant_id OR mort<>1 OR bal<amount THEN RAISE_APPLICATION_ERROR(-20089,'Для выкупа нужно 110% первоначальной цены'); END IF; UPDATE "УЧАСТНИКИ" SET "БАЛАНС"="БАЛАНС"-amount WHERE "ID_УЧАСТНИКА"=p_participant_id; UPDATE "ВЛАДЕНИЯ" SET "ЗАЛОЖЕНА"=0 WHERE "ID_ВЛАДЕНИЯ"=p_ownership_id; add_action(g,p_participant_id,cell,'СНЯТИЕ_ЗАЛОГА',amount); END;
 PROCEDURE start_auction(p_game_id NUMBER,p_cell_id NUMBER) IS n NUMBER; price NUMBER; owner NUMBER; state VARCHAR2(40); BEGIN SELECT "КОД_СОСТОЯНИЯ_ХОДА" INTO state FROM "ИГРЫ" WHERE "ID_ИГРЫ"=p_game_id FOR UPDATE; IF state<>'ОЖИДАНИЕ_ПОКУПКИ' THEN RAISE_APPLICATION_ERROR(-20090,'Аукцион нельзя начать'); END IF; SELECT COUNT(*) INTO n FROM "АУКЦИОНЫ" WHERE "ID_ИГРЫ"=p_game_id AND "КОД_СТАТУСА_АУКЦИОНА"='АКТИВЕН'; IF n>0 THEN RAISE_APPLICATION_ERROR(-20091,'Другой аукцион активен'); END IF; SELECT v."ID_ВЛАДЕЛЬЦА",c."ЦЕНА_ПОКУПКИ" INTO owner,price FROM "ВЛАДЕНИЯ" v JOIN "КЛЕТКИ" c ON c."ID_КЛЕТКИ"=v."ID_КЛЕТКИ" WHERE v."ID_ИГРЫ"=p_game_id AND v."ID_КЛЕТКИ"=p_cell_id FOR UPDATE; IF owner IS NOT NULL THEN RAISE_APPLICATION_ERROR(-20092,'Клетка куплена'); END IF; INSERT INTO "АУКЦИОНЫ"("ID_ИГРЫ","ID_КЛЕТКИ","КОД_СТАТУСА_АУКЦИОНА","СТАРТ_ЦЕНА","ДАТА_НАЧАЛА") VALUES(p_game_id,p_cell_id,'АКТИВЕН',FLOOR(price/2),SYSDATE); UPDATE "ИГРЫ" SET "КОД_СОСТОЯНИЯ_ХОДА"='ПРОВЕДЕНИЕ_АУКЦИОНА' WHERE "ID_ИГРЫ"=p_game_id; END;
 PROCEDURE make_bid(p_auction_id NUMBER,p_participant_id NUMBER,p_amount NUMBER) IS g NUMBER; st VARCHAR2(40); startp NUMBER; started DATE; pg NUMBER; ps VARCHAR2(40); bal NUMBER; init NUMBER; eligible NUMBER; answered NUMBER; BEGIN SELECT "ID_ИГРЫ","КОД_СТАТУСА_АУКЦИОНА","СТАРТ_ЦЕНА","ДАТА_НАЧАЛА" INTO g,st,startp,started FROM "АУКЦИОНЫ" WHERE "ID_АУКЦИОНА"=p_auction_id FOR UPDATE; SELECT u."ID_ИГРЫ",u."КОД_СТАТУСА_УЧАСТНИКА",u."БАЛАНС",x."ID_ТЕКУЩЕГО_УЧАСТНИКА" INTO pg,ps,bal,init FROM "УЧАСТНИКИ" u JOIN "ИГРЫ" x ON x."ID_ИГРЫ"=u."ID_ИГРЫ" WHERE u."ID_УЧАСТНИКА"=p_participant_id; IF st<>'АКТИВЕН' OR pg<>g OR ps<>'АКТИВЕН' OR p_participant_id=init THEN RAISE_APPLICATION_ERROR(-20093,'Ставка недоступна'); END IF; IF SYSDATE>=started+c_auction_seconds/86400 THEN RAISE_APPLICATION_ERROR(-20094,'Время истекло'); END IF; IF p_amount<>0 AND(p_amount<startp OR p_amount>bal) THEN RAISE_APPLICATION_ERROR(-20095,'Ставка должна быть от стартовой цены до вашего баланса'); END IF; MERGE INTO "СТАВКИ" s USING(SELECT p_auction_id a,p_participant_id p,p_amount m FROM dual) x ON(s."ID_АУКЦИОНА"=x.a AND s."ID_УЧАСТНИКА"=x.p) WHEN MATCHED THEN UPDATE SET s."СУММА"=x.m,s."ДАТА_ВРЕМЯ"=SYSDATE WHEN NOT MATCHED THEN INSERT("ID_АУКЦИОНА","ID_УЧАСТНИКА","СУММА","ДАТА_ВРЕМЯ") VALUES(x.a,x.p,x.m,SYSDATE); SELECT COUNT(*) INTO eligible FROM "УЧАСТНИКИ" WHERE "ID_ИГРЫ"=g AND "КОД_СТАТУСА_УЧАСТНИКА"='АКТИВЕН' AND "ID_УЧАСТНИКА"<>init; SELECT COUNT(*) INTO answered FROM "СТАВКИ" s JOIN "УЧАСТНИКИ" u ON u."ID_УЧАСТНИКА"=s."ID_УЧАСТНИКА" WHERE s."ID_АУКЦИОНА"=p_auction_id AND u."КОД_СТАТУСА_УЧАСТНИКА"='АКТИВЕН' AND s."ID_УЧАСТНИКА"<>init; IF eligible>0 AND answered=eligible THEN close_auction(p_auction_id); END IF; END;
 PROCEDURE close_auction(p_auction_id NUMBER) IS g NUMBER; cell NUMBER; st VARCHAR2(40); started DATE; init NUMBER; winner NUMBER:=NULL; amount NUMBER:=NULL; eligible NUMBER; answered NUMBER; BEGIN SELECT a."ID_ИГРЫ",a."ID_КЛЕТКИ",a."КОД_СТАТУСА_АУКЦИОНА",a."ДАТА_НАЧАЛА",x."ID_ТЕКУЩЕГО_УЧАСТНИКА" INTO g,cell,st,started,init FROM "АУКЦИОНЫ" a JOIN "ИГРЫ" x ON x."ID_ИГРЫ"=a."ID_ИГРЫ" WHERE a."ID_АУКЦИОНА"=p_auction_id FOR UPDATE; IF st<>'АКТИВЕН' THEN RETURN; END IF; SELECT COUNT(*) INTO eligible FROM "УЧАСТНИКИ" WHERE "ID_ИГРЫ"=g AND "КОД_СТАТУСА_УЧАСТНИКА"='АКТИВЕН' AND "ID_УЧАСТНИКА"<>init; SELECT COUNT(*) INTO answered FROM "СТАВКИ" s JOIN "УЧАСТНИКИ" u ON u."ID_УЧАСТНИКА"=s."ID_УЧАСТНИКА" WHERE s."ID_АУКЦИОНА"=p_auction_id AND u."КОД_СТАТУСА_УЧАСТНИКА"='АКТИВЕН' AND s."ID_УЧАСТНИКА"<>init; IF SYSDATE<started+c_auction_seconds/86400 AND NOT(eligible>0 AND answered=eligible) THEN RAISE_APPLICATION_ERROR(-20096,'Аукцион ещё идёт'); END IF; BEGIN SELECT "ID_УЧАСТНИКА","СУММА" INTO winner,amount FROM(SELECT s."ID_УЧАСТНИКА",s."СУММА" FROM "СТАВКИ" s JOIN "УЧАСТНИКИ" u ON u."ID_УЧАСТНИКА"=s."ID_УЧАСТНИКА" WHERE s."ID_АУКЦИОНА"=p_auction_id AND s."СУММА">0 AND s."ID_УЧАСТНИКА"<>init AND u."КОД_СТАТУСА_УЧАСТНИКА"='АКТИВЕН' AND u."БАЛАНС">=s."СУММА" ORDER BY s."СУММА" DESC,s."ДАТА_ВРЕМЯ",s."ID_СТАВКИ") WHERE ROWNUM=1; EXCEPTION WHEN NO_DATA_FOUND THEN NULL; END; IF winner IS NOT NULL THEN UPDATE "УЧАСТНИКИ" SET "БАЛАНС"="БАЛАНС"-amount WHERE "ID_УЧАСТНИКА"=winner; UPDATE "ВЛАДЕНИЯ" SET "ID_ВЛАДЕЛЬЦА"=winner WHERE "ID_ИГРЫ"=g AND "ID_КЛЕТКИ"=cell; UPDATE "АУКЦИОНЫ" SET "ID_ПОБЕДИТЕЛЯ"=winner,"ФИНАЛ_ЦЕНА"=amount,"КОД_СТАТУСА_АУКЦИОНА"='ЗАВЕРШЕН',"ДАТА_ОКОНЧАНИЯ"=SYSDATE WHERE "ID_АУКЦИОНА"=p_auction_id; add_action(g,winner,cell,'АУКЦИОН',amount); ELSE UPDATE "АУКЦИОНЫ" SET "КОД_СТАТУСА_АУКЦИОНА"='НЕ_СОСТОЯЛСЯ',"ДАТА_ОКОНЧАНИЯ"=SYSDATE WHERE "ID_АУКЦИОНА"=p_auction_id; add_action(g,NULL,cell,'АУКЦИОН',NULL); END IF; advance_to_next_player(g); END;
 PROCEDURE handle_timeout(p_game_id NUMBER) IS pid NUMBER; cnt NUMBER; bal NUMBER; BEGIN SELECT "ID_ТЕКУЩЕГО_УЧАСТНИКА" INTO pid FROM "ИГРЫ" WHERE "ID_ИГРЫ"=p_game_id FOR UPDATE; SELECT "КОЛ_ТАЙМАУТОВ" INTO cnt FROM "УЧАСТНИКИ" WHERE "ID_УЧАСТНИКА"=pid FOR UPDATE; IF cnt>=1 THEN UPDATE "УЧАСТНИКИ" SET "КОЛ_ТАЙМАУТОВ"=2 WHERE "ID_УЧАСТНИКА"=pid; add_action(p_game_id,pid,NULL,'ТАЙМ_АУТ',NULL); declare_bankruptcy(pid,c_bankruptcy_second_timeout); ELSE UPDATE "УЧАСТНИКИ" SET "КОЛ_ТАЙМАУТОВ"=1,"БАЛАНС"="БАЛАНС"-c_timeout_penalty WHERE "ID_УЧАСТНИКА"=pid; add_action(p_game_id,pid,NULL,'ТАЙМ_АУТ',c_timeout_penalty); SELECT "БАЛАНС" INTO bal FROM "УЧАСТНИКИ" WHERE "ID_УЧАСТНИКА"=pid; IF bal<0 THEN UPDATE "ИГРЫ" SET "КОД_СОСТОЯНИЯ_ХОДА"='ПОКРЫТИЕ_ДОЛГА',"ВРЕМЯ_НАЧАЛА_ХОДА"=SYSDATE WHERE "ID_ИГРЫ"=p_game_id; ELSE advance_to_next_player(p_game_id); END IF; END IF; END;
 PROCEDURE check_game_timer(p_game_id NUMBER) IS state VARCHAR2(40); started DATE; gst VARCHAR2(40); aid NUMBER; pid NUMBER; host_id NUMBER; BEGIN SELECT "КОД_СОСТОЯНИЯ_ХОДА","ВРЕМЯ_НАЧАЛА_ХОДА","КОД_СТАТУСА_ИГРЫ","ID_ТЕКУЩЕГО_УЧАСТНИКА","ID_ХОСТА" INTO state,started,gst,pid,host_id FROM "ИГРЫ" WHERE "ID_ИГРЫ"=p_game_id FOR UPDATE; IF gst='ПРОВЕРКА_ГОТОВНОСТИ' THEN IF started IS NOT NULL AND SYSDATE>=started+c_ready_seconds/86400 THEN start_game(p_game_id,host_id); END IF; RETURN; END IF; IF gst<>'АКТИВНА' THEN RETURN; END IF; IF state IN('ОЖИДАНИЕ_БРОСКА','ОЖИДАНИЕ_ПОКУПКИ','ОЖИДАНИЕ_УЛУЧШЕНИЯ','ЗАВЕРШЕНИЕ_ХОДА') AND SYSDATE>=started+c_turn_minutes/1440 THEN handle_timeout(p_game_id); ELSIF state='ПОКРЫТИЕ_ДОЛГА' AND SYSDATE>=started+c_turn_minutes/1440 THEN declare_bankruptcy(pid,c_bankruptcy_debt_timeout); ELSIF state='ПРОВЕДЕНИЕ_АУКЦИОНА' THEN BEGIN SELECT "ID_АУКЦИОНА" INTO aid FROM "АУКЦИОНЫ" WHERE "ID_ИГРЫ"=p_game_id AND "КОД_СТАТУСА_АУКЦИОНА"='АКТИВЕН'; close_auction(aid); EXCEPTION WHEN NO_DATA_FOUND THEN NULL; WHEN OTHERS THEN IF SQLCODE=-20096 THEN NULL; ELSE RAISE; END IF; END; END IF; END;
 PROCEDURE finish_game(p_game_id NUMBER,p_winner_id NUMBER DEFAULT NULL) IS st VARCHAR2(40); n NUMBER; BEGIN SELECT "КОД_СТАТУСА_ИГРЫ" INTO st FROM "ИГРЫ" WHERE "ID_ИГРЫ"=p_game_id FOR UPDATE; IF st IN('ЗАВЕРШЕНА','ЗАБРОШЕНА') THEN RETURN; END IF; IF p_winner_id IS NOT NULL THEN SELECT COUNT(*) INTO n FROM "УЧАСТНИКИ" WHERE "ID_УЧАСТНИКА"=p_winner_id AND "ID_ИГРЫ"=p_game_id; IF n=0 THEN RAISE_APPLICATION_ERROR(-20100,'Победитель из другой игры'); END IF; END IF; UPDATE "ИГРЫ" SET "КОД_СТАТУСА_ИГРЫ"='ЗАВЕРШЕНА',"ДАТА_ЗАВЕРШЕНИЯ"=SYSDATE,"ID_ПОБЕДИТЕЛЯ"=p_winner_id,"ID_ТЕКУЩЕГО_УЧАСТНИКА"=NULL,"КОД_СОСТОЯНИЯ_ХОДА"=NULL,"ВРЕМЯ_НАЧАЛА_ХОДА"=NULL WHERE "ID_ИГРЫ"=p_game_id; END;
 PROCEDURE finish_or_continue(p_game_id NUMBER) IS n NUMBER; winner NUMBER; BEGIN SELECT COUNT(*) INTO n FROM "УЧАСТНИКИ" WHERE "ID_ИГРЫ"=p_game_id AND "КОД_СТАТУСА_УЧАСТНИКА"='АКТИВЕН'; IF n=1 THEN SELECT "ID_УЧАСТНИКА" INTO winner FROM "УЧАСТНИКИ" WHERE "ID_ИГРЫ"=p_game_id AND "КОД_СТАТУСА_УЧАСТНИКА"='АКТИВЕН'; finish_game(p_game_id,winner); ELSIF n=0 THEN finish_game(p_game_id,NULL); END IF; END;
 PROCEDURE declare_bankruptcy(p_participant_id NUMBER,p_reason VARCHAR2) IS g NUMBER; bal NUMBER; cur NUMBER; avail NUMBER; gst VARCHAR2(40); BEGIN IF p_reason NOT IN(c_bankruptcy_voluntary,c_bankruptcy_debt_timeout,c_bankruptcy_second_timeout) THEN RAISE_APPLICATION_ERROR(-20101,'Неизвестная причина'); END IF; SELECT u."ID_ИГРЫ",u."БАЛАНС",x."ID_ТЕКУЩЕГО_УЧАСТНИКА" INTO g,bal,cur FROM "УЧАСТНИКИ" u JOIN "ИГРЫ" x ON x."ID_ИГРЫ"=u."ID_ИГРЫ" WHERE u."ID_УЧАСТНИКА"=p_participant_id FOR UPDATE; IF p_reason=c_bankruptcy_voluntary THEN IF bal>=0 THEN RAISE_APPLICATION_ERROR(-20102,'Нет долга'); END IF; SELECT COUNT(*) INTO avail FROM "ВЛАДЕНИЯ" WHERE "ID_ВЛАДЕЛЬЦА"=p_participant_id AND("КОЛВО_ДОМОВ">0 OR("ЗАЛОЖЕНА"=0 AND "КОЛВО_ДОМОВ"=0)); IF avail>0 THEN RAISE_APPLICATION_ERROR(-20103,'Осталось доступное имущество'); END IF; END IF; UPDATE "УЧАСТНИКИ" SET "КОД_СТАТУСА_УЧАСТНИКА"='БАНКРОТ' WHERE "ID_УЧАСТНИКА"=p_participant_id; return_properties_to_bank(p_participant_id); add_action(g,p_participant_id,NULL,'БАНКРОТСТВО',bal); finish_or_continue(g); SELECT "КОД_СТАТУСА_ИГРЫ" INTO gst FROM "ИГРЫ" WHERE "ID_ИГРЫ"=g; IF gst='АКТИВНА' AND cur=p_participant_id THEN advance_to_next_player(g); END IF; END;
 PROCEDURE leave_active_game(p_participant_id NUMBER) IS g NUMBER; cur NUMBER; gst VARCHAR2(40); n NUMBER; BEGIN SELECT u."ID_ИГРЫ",x."ID_ТЕКУЩЕГО_УЧАСТНИКА",x."КОД_СТАТУСА_ИГРЫ" INTO g,cur,gst FROM "УЧАСТНИКИ" u JOIN "ИГРЫ" x ON x."ID_ИГРЫ"=u."ID_ИГРЫ" WHERE u."ID_УЧАСТНИКА"=p_participant_id FOR UPDATE; IF gst<>'АКТИВНА' THEN RAISE_APPLICATION_ERROR(-20104,'Игра не активна'); END IF; SELECT COUNT(*) INTO n FROM "АУКЦИОНЫ" WHERE "ID_ИГРЫ"=g AND "КОД_СТАТУСА_АУКЦИОНА"='АКТИВЕН'; IF n>0 THEN RAISE_APPLICATION_ERROR(-20105,'Нельзя выйти во время аукциона'); END IF; UPDATE "УЧАСТНИКИ" SET "КОД_СТАТУСА_УЧАСТНИКА"='БАНКРОТ' WHERE "ID_УЧАСТНИКА"=p_participant_id; return_properties_to_bank(p_participant_id); add_action(g,p_participant_id,NULL,'ВЫХОД_УЧАСТНИКА',NULL); add_action(g,p_participant_id,NULL,'БАНКРОТСТВО',NULL); finish_or_continue(g); SELECT "КОД_СТАТУСА_ИГРЫ" INTO gst FROM "ИГРЫ" WHERE "ID_ИГРЫ"=g; IF gst='АКТИВНА' AND cur=p_participant_id THEN advance_to_next_player(g); END IF; END;
 PROCEDURE disconnect_player(p_participant_id NUMBER) IS g NUMBER; cur NUMBER; gst VARCHAR2(40); BEGIN SELECT u."ID_ИГРЫ",x."ID_ТЕКУЩЕГО_УЧАСТНИКА",x."КОД_СТАТУСА_ИГРЫ" INTO g,cur,gst FROM "УЧАСТНИКИ" u JOIN "ИГРЫ" x ON x."ID_ИГРЫ"=u."ID_ИГРЫ" WHERE u."ID_УЧАСТНИКА"=p_participant_id FOR UPDATE; IF gst<>'АКТИВНА' THEN RETURN; END IF; UPDATE "УЧАСТНИКИ" SET "КОД_СТАТУСА_УЧАСТНИКА"='БАНКРОТ' WHERE "ID_УЧАСТНИКА"=p_participant_id AND "КОД_СТАТУСА_УЧАСТНИКА"='АКТИВЕН'; IF SQL%ROWCOUNT=0 THEN RETURN; END IF; return_properties_to_bank(p_participant_id); add_action(g,p_participant_id,NULL,'ВЫХОД_УЧАСТНИКА',NULL); add_action(g,p_participant_id,NULL,'БАНКРОТСТВО',NULL); finish_or_continue(g); SELECT "КОД_СТАТУСА_ИГРЫ" INTO gst FROM "ИГРЫ" WHERE "ID_ИГРЫ"=g; IF gst='АКТИВНА' AND cur=p_participant_id THEN advance_to_next_player(g); END IF; END;
 PROCEDURE send_message(p_participant_id NUMBER,p_text VARCHAR2) IS ps VARCHAR2(40); gs VARCHAR2(40); BEGIN IF TRIM(p_text) IS NULL THEN RAISE_APPLICATION_ERROR(-20110,'Пустое сообщение'); END IF; SELECT u."КОД_СТАТУСА_УЧАСТНИКА",g."КОД_СТАТУСА_ИГРЫ" INTO ps,gs FROM "УЧАСТНИКИ" u JOIN "ИГРЫ" g ON g."ID_ИГРЫ"=u."ID_ИГРЫ" WHERE u."ID_УЧАСТНИКА"=p_participant_id; IF ps NOT IN('В_ЛОББИ','АКТИВЕН') OR gs='ЗАБРОШЕНА' THEN RAISE_APPLICATION_ERROR(-20111,'Чат недоступен'); END IF; INSERT INTO "ЧАТ"("ID_УЧАСТНИКА","ТЕКСТ","ДАТА_ВРЕМЯ") VALUES(p_participant_id,TRIM(p_text),SYSDATE); END;
 FUNCTION get_chat(p_participant_id NUMBER) RETURN SYS_REFCURSOR IS rc SYS_REFCURSOR; g NUMBER; ps VARCHAR2(40); BEGIN SELECT "ID_ИГРЫ","КОД_СТАТУСА_УЧАСТНИКА" INTO g,ps FROM "УЧАСТНИКИ" WHERE "ID_УЧАСТНИКА"=p_participant_id; IF ps NOT IN('В_ЛОББИ','АКТИВЕН') THEN RAISE_APPLICATION_ERROR(-20112,'Чат недоступен'); END IF; OPEN rc FOR SELECT c."ID_СООБЩЕНИЯ",p."ЛОГИН",c."ТЕКСТ",c."ДАТА_ВРЕМЯ" FROM "ЧАТ" c JOIN "УЧАСТНИКИ" u ON u."ID_УЧАСТНИКА"=c."ID_УЧАСТНИКА" JOIN "ПОЛЬЗОВАТЕЛИ" p ON p."ID_ПОЛЬЗОВАТЕЛЯ"=u."ID_ПОЛЬЗОВАТЕЛЯ" WHERE u."ID_ИГРЫ"=g ORDER BY c."ДАТА_ВРЕМЯ",c."ID_СООБЩЕНИЯ"; RETURN rc; END;
 FUNCTION get_action_log(p_participant_id NUMBER) RETURN SYS_REFCURSOR IS rc SYS_REFCURSOR; g NUMBER; BEGIN g:=participant_game(p_participant_id); OPEN rc FOR SELECT * FROM(SELECT j."ID_ДЕЙСТВИЯ",j."ДАТА_ВРЕМЯ",j."КОД_ДЕЙСТВИЯ",t."НАИМЕНОВАНИЕ" "ДЕЙСТВИЕ",p."ЛОГИН",c."НАЗВАНИЕ" "КЛЕТКА",j."СУММА",CASE WHEN j."КОД_ДЕЙСТВИЯ"='ОПЛАТА_АРЕНДЫ' THEN(SELECT op."ЛОГИН" FROM "ВЛАДЕНИЯ" v JOIN "УЧАСТНИКИ" ou ON ou."ID_УЧАСТНИКА"=v."ID_ВЛАДЕЛЬЦА" JOIN "ПОЛЬЗОВАТЕЛИ" op ON op."ID_ПОЛЬЗОВАТЕЛЯ"=ou."ID_ПОЛЬЗОВАТЕЛЯ" WHERE v."ID_ИГРЫ"=j."ID_ИГРЫ" AND v."ID_КЛЕТКИ"=j."ID_КЛЕТКИ") END "ПОЛУЧАТЕЛЬ" FROM "ЖУРНАЛ_ДЕЙСТВИЙ" j LEFT JOIN "УЧАСТНИКИ" u ON u."ID_УЧАСТНИКА"=j."ID_УЧАСТНИКА" LEFT JOIN "ПОЛЬЗОВАТЕЛИ" p ON p."ID_ПОЛЬЗОВАТЕЛЯ"=u."ID_ПОЛЬЗОВАТЕЛЯ" LEFT JOIN "КЛЕТКИ" c ON c."ID_КЛЕТКИ"=j."ID_КЛЕТКИ" JOIN "ТИПЫ_ДЕЙСТВИЙ" t ON t."КОД_ДЕЙСТВИЯ"=j."КОД_ДЕЙСТВИЯ" WHERE j."ID_ИГРЫ"=g ORDER BY j."ID_ДЕЙСТВИЯ" DESC) WHERE ROWNUM<=80 ORDER BY "ID_ДЕЙСТВИЯ"; RETURN rc; END;
 FUNCTION get_player_stats(p_user_id NUMBER) RETURN SYS_REFCURSOR IS rc SYS_REFCURSOR; BEGIN OPEN rc FOR WITH played AS(SELECT u."ID_УЧАСТНИКА",u."ID_ИГРЫ",g."ID_ПОБЕДИТЕЛЯ" FROM "УЧАСТНИКИ" u JOIN "ИГРЫ" g ON g."ID_ИГРЫ"=u."ID_ИГРЫ" WHERE u."ID_ПОЛЬЗОВАТЕЛЯ"=p_user_id AND u."ОЧЕРЕДЬ_ХОДА" IS NOT NULL AND g."КОД_СТАТУСА_ИГРЫ"='ЗАВЕРШЕНА'),fav AS(SELECT c."НАЗВАНИЕ",COUNT(*) cnt,ROW_NUMBER() OVER(ORDER BY COUNT(*) DESC,c."ПОЗИЦИЯ") rn FROM "ЖУРНАЛ_ДЕЙСТВИЙ" j JOIN "УЧАСТНИКИ" u ON u."ID_УЧАСТНИКА"=j."ID_УЧАСТНИКА" JOIN "КЛЕТКИ" c ON c."ID_КЛЕТКИ"=j."ID_КЛЕТКИ" JOIN "ИГРЫ" g ON g."ID_ИГРЫ"=j."ID_ИГРЫ" WHERE u."ID_ПОЛЬЗОВАТЕЛЯ"=p_user_id AND j."КОД_ДЕЙСТВИЯ"='ПОСЕЩЕНИЕ_КЛЕТКИ' AND g."КОД_СТАТУСА_ИГРЫ"='ЗАВЕРШЕНА' GROUP BY c."НАЗВАНИЕ",c."ПОЗИЦИЯ") SELECT p."ЛОГИН",COUNT(pl."ID_ИГРЫ") "КОЛИЧЕСТВО_ИГР",NVL(SUM(CASE WHEN pl."ID_ПОБЕДИТЕЛЯ"=pl."ID_УЧАСТНИКА" THEN 1 ELSE 0 END),0) "ПОБЕДЫ",CASE WHEN COUNT(pl."ID_ИГРЫ")=0 THEN 0 ELSE ROUND(100*SUM(CASE WHEN pl."ID_ПОБЕДИТЕЛЯ"=pl."ID_УЧАСТНИКА" THEN 1 ELSE 0 END)/COUNT(pl."ID_ИГРЫ"),2) END "ПРОЦЕНТ_ПОБЕД",(SELECT "НАЗВАНИЕ" FROM fav WHERE rn=1) "ЛЮБИМАЯ_КЛЕТКА" FROM "ПОЛЬЗОВАТЕЛИ" p LEFT JOIN played pl ON 1=1 WHERE p."ID_ПОЛЬЗОВАТЕЛЯ"=p_user_id GROUP BY p."ЛОГИН"; RETURN rc; END;
 FUNCTION get_leaderboard RETURN SYS_REFCURSOR IS rc SYS_REFCURSOR; BEGIN OPEN rc FOR SELECT p."ID_ПОЛЬЗОВАТЕЛЯ",p."ЛОГИН",COUNT(g."ID_ИГРЫ") "ИГРЫ",NVL(SUM(CASE WHEN g."ID_ПОБЕДИТЕЛЯ"=u."ID_УЧАСТНИКА" THEN 1 ELSE 0 END),0) "ПОБЕДЫ",CASE WHEN COUNT(g."ID_ИГРЫ")=0 THEN 0 ELSE ROUND(100*SUM(CASE WHEN g."ID_ПОБЕДИТЕЛЯ"=u."ID_УЧАСТНИКА" THEN 1 ELSE 0 END)/COUNT(g."ID_ИГРЫ"),2) END "ПРОЦЕНТ" FROM "ПОЛЬЗОВАТЕЛИ" p LEFT JOIN "УЧАСТНИКИ" u ON u."ID_ПОЛЬЗОВАТЕЛЯ"=p."ID_ПОЛЬЗОВАТЕЛЯ" AND u."ОЧЕРЕДЬ_ХОДА" IS NOT NULL LEFT JOIN "ИГРЫ" g ON g."ID_ИГРЫ"=u."ID_ИГРЫ" AND g."КОД_СТАТУСА_ИГРЫ"='ЗАВЕРШЕНА' GROUP BY p."ID_ПОЛЬЗОВАТЕЛЯ",p."ЛОГИН" ORDER BY "ПРОЦЕНТ" DESC,"ПОБЕДЫ" DESC,"ИГРЫ" DESC,p."ЛОГИН"; RETURN rc; END;
 FUNCTION get_game_history(p_user_id NUMBER) RETURN SYS_REFCURSOR IS rc SYS_REFCURSOR; BEGIN OPEN rc FOR SELECT g."ID_ИГРЫ",g."НАЗВАНИЕ",g."ДАТА_СТАРТА",g."ДАТА_ЗАВЕРШЕНИЯ",u."БАЛАНС" "ИТОГОВЫЙ_БАЛАНС",u."КОД_СТАТУСА_УЧАСТНИКА",wp."ЛОГИН" "ПОБЕДИТЕЛЬ",CASE WHEN g."ID_ПОБЕДИТЕЛЯ"=u."ID_УЧАСТНИКА" THEN 'Победа' ELSE 'Поражение' END "РЕЗУЛЬТАТ" FROM "УЧАСТНИКИ" u JOIN "ИГРЫ" g ON g."ID_ИГРЫ"=u."ID_ИГРЫ" LEFT JOIN "УЧАСТНИКИ" wu ON wu."ID_УЧАСТНИКА"=g."ID_ПОБЕДИТЕЛЯ" LEFT JOIN "ПОЛЬЗОВАТЕЛИ" wp ON wp."ID_ПОЛЬЗОВАТЕЛЯ"=wu."ID_ПОЛЬЗОВАТЕЛЯ" WHERE u."ID_ПОЛЬЗОВАТЕЛЯ"=p_user_id AND u."ОЧЕРЕДЬ_ХОДА" IS NOT NULL AND g."КОД_СТАТУСА_ИГРЫ"='ЗАВЕРШЕНА' ORDER BY g."ДАТА_ЗАВЕРШЕНИЯ" DESC; RETURN rc; END;
END monopoly;
/
SHOW ERRORS PACKAGE BODY monopoly;
