CREATE TABLE network_test_messages (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    sender_name    VARCHAR2(50) NOT NULL,
    message_text   VARCHAR2(200) NOT NULL,
    sent_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_network_test_messages
        PRIMARY KEY (id)
);


SELECT table_name
FROM user_tables
WHERE table_name = 'NETWORK_TEST_MESSAGES';